### ISSUE TITLE
Error with dual variables when using complex variables and boolean variables

### ISSUE THREAD

**Issue by zach401** [cvxpy/cvxpy#1133]
**Describe the bug**
When solving a model with some boolean and some complex variables, CVXPY produces a KeyError when trying to extract the dual variables within invert() in complex2real.py. 

**To Reproduce**
```
import cvxpy as cp

bool_var = cp.Variable(boolean=True)
complex_var = cp.Variable(complex=True)

constraints = [
    cp.real(complex_var) <= bool_var,
]

obj = cp.Maximize(cp.real(complex_var))
prob = cp.Problem(obj, constraints)
prob.solve(solver='GUROBI')
print(prob.value)
```

**Expected behavior**
Expected objective value, in this case 1. 

**Output**
```
Traceback (most recent call last):
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/minimal_example.py", line 12, in <module>
    prob.solve(solver='GUROBI')
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/venv/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/venv/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 748, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/venv/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1052, in unpack_results
    solution = chain.invert(solution, inverse_data)
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/venv/lib/python3.8/site-packages/cvxpy/reductions/chain.py", line 79, in invert
    solution = r.invert(solution, inv)
  File "/Users/zach401/Documents/Caltech/Research/ACN/Projects/PWP2020/venv/lib/python3.8/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 99, in invert
    dvars[cid] = solution.dual_vars[cid]
KeyError: 5
```
**Version**
 - OS: macOS 10.15.6
 - CVXPY Version: 1.1.5

**Additional context**
Error occurs when solving with Gurobi or Mosek with complex and boolean variables, but not when either type is used in isolation. 

I was able to prevent the error by updated line 99 of complex2real.py to 
`dvars[cid] = solution.dual_vars.get(cid)`

However I don't know if this would be the preferred solution.

**Comment by rileyjmurray** [comment]
Hi Zach! Fancy seeing you here. I believe your fix is valid. Certainly, no attempt should be made to recover dual variables for mixed-integer problems. I actually didn't know that calling ``.get(k)`` on a dict returned ``None`` if the key isn't in the dictionary.

The only possible improvement would be to check for integer variables before entering the loop where that line is getting hit. The entire loop is actually quite long https://github.com/cvxgrp/cvxpy/blob/494f79ce0e24cd59153dfe395b8ac833715ce5d8/cvxpy/reductions/complex2real/complex2real.py#L97-L123.
Based on the ``pass`` statement on line 116 it's clear that there is no harm in not populating the dict ``dvars``. So I think the thing to do is check for mixed-integer before entering the loop, and if so return
```
return Solution(solution.status, solution.opt_val, pvars, dvars, solution.attr)
```
for good measure, when ``pvars`` and ``dvars`` are declared on lines 71-72, they should be instantiated unambiguously as dicts ``pvars, dvars = dict(), dict()``.
