### ISSUE TITLE
AttributeError while installing cvxpy...

### ISSUE THREAD

**Issue by leeway00** [cvxpy/cvxpy#1195]
**Describe the bug**
While installing the package, I got and AttributeError
I checked the numpy, scipy and setuptools versions, but none of them are problem.
How can I solve this?

**Expected behavior**
It should be installed...

**Output**
```
Collecting cvxpy
  Using cached cvxpy-1.1.7.tar.gz (1.0 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lr77xklw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy >= 1.15' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/usr/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lr77xklw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy >= 1.15' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Version**
 - OS: CentOS Linux release 7.5.1804
 - CVXPY Version: 1.1.7

**Comment by quantumiracle** [comment]
This works for me:
`pip uninstall -y enum34
`
