### ISSUE TITLE
Cannot import name '_cvxcore'

### ISSUE THREAD

**Issue by oledoit** [cvxpy/cvxpy#1243]
I am calling cvxpy from Matlab thanks to its interface to Python. But the cvxcore module is trying to load a "_cvxcore" that does not exist. The __init__.py file for cvxcore reads as follows:

**TODO(akshayka): This is a hack; the swig-auto-generated cvxcore.py
tries to import cvxcore as `from . import _cvxcore`
import _cvxcore**
 
The so-called "undescore hack" is clearly not working in this case, so it would be desirable to have a proper fix. I assume that akshayka is Akshay Agrawal.

**To Reproduce**
I type this at the Matlab prompt:
py.importlib.import_module('cvxpy')

**Expected behavior**
It should not give any Python error message, meaning that Matlab accepts the package.

**Output**
Error using cvxcore><module> (line 13)
Python Error: ImportError: cannot import name '_cvxcore' from 'cvxpy.cvxcore.python'
(C:\Users\ledoi\anaconda3\envs\cvxpy\Lib\site-packages\cvxpy\cvxcore\python\__init__.py)

Error in canonInterface><module> (line 17)
import cvxpy.cvxcore.python.cvxcore as cvxcore

Error in affine_atom><module> (line 22)
from cvxpy.cvxcore.python import canonInterface

Error in hstack><module> (line 18)
from cvxpy.atoms.affine.affine_atom import AffAtom

Error in reshape><module> (line 18)
from cvxpy.atoms.affine.hstack import hstack

Error in power_tools><module> (line 18)
from cvxpy.atoms.affine.reshape import reshape

Error in geo_mean><module> (line 20)
from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,

Error in __init__><module> (line 20)
from cvxpy.atoms.geo_mean import geo_mean

Error in __init__><module> (line 18)
from cvxpy.atoms import *

Error in <frozen importlib>_call_with_frames_removed (line 219)

Error in <frozen importlib>exec_module (line 728)

Error in <frozen importlib>_load_unlocked (line 677)

Error in <frozen importlib>_find_and_load_unlocked (line 967)

Error in <frozen importlib>_find_and_load (line 983)

Error in <frozen importlib>_gcd_import (line 1006)

Error in __init__>import_module (line 127)
    return _bootstrap._gcd_import(name[level:], package, level)

**Version**
 - OS: Microsoft Windows 10
 - CVXPY Version: 1.1
 - Python Version: 3.7.6
 - Matlab Version: R2019b
 - Anaconda Version: 1.9.12

**Additional context**
I can use cvxpy successfully from the Anaconda command line, so the " underscore hack" does work in some limited contexts. Also, I can call other packages successfully from Matlab, such as numpy and pandas, so the problem is not between Matlab and Python in general. I'd be happy to have a "quick and dirty" fix, even if it means just hacking into the swig-auto-generated cvxcore.py file, or some init.py file.

**Comment by akshayka** [comment]
Thanks for reporting.

This doesn't appear to be related to the _cvxcore C++ extension module, but rather to the Python binding if I understand the error message correctly

I'm not sure why Python invoked from MATLAB would be unable to find the Python module cvxcore. Errors like these usually suggest that the installation is somehow broken.

@rileyjmurray , have you seen anything like this on Windows?

**Comment by rileyjmurray** [comment]
I haven't seen an error like this before. I just tried to import cvxpy from matlab and my matlab instance hung for several minutes with "busy" before crashing entirely. (I'm also running R2019b and tested this on python 3.7.)

@oledoit can you run ``import _cvxcore`` from matlab? That command works for me when within the python interpreter.

**Comment by Kesleroman** [comment]
I am not 100% sure, however, this issue seems to be quite similar to the issue with which I have encountered recently.

I use _**Pyinstaller**_ for creating an executable file out of my Python project. In the project I imported the **_cvxpy_** library.
After creating the .exe file It works perfectly on my local environment. However, if I try to execute the program on the other environment which does not have installed Python I got the following error:

**Traceback (most recent call last):
  File "myMain.py", line 1, in <module> 
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\__init__.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\atoms\__init__.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\atoms\geo_mean.py", line 20, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\utilities\power_tools.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\atoms\affine\reshape.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\atoms\affine\hstack.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\atoms\affine\affine_atom.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "cvxpy\cvxcore\python\__init__.py", line 3, in <module>
ImportError: DLL load failed while importing _cvxcore: The specified module could not be found.
[2960] Failed to execute script myMain**

**Comment by pizquierdo2** [comment]
I have a similar problem. Today I updated cvxpy and then when I tried to run my python files where I use cxvpy I  have got 
```
Traceback (most recent call last):
  File "name_file", line 1, in <module>
    import cvxpy as cp
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/atoms/geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/utilities/power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/atoms/affine/reshape.py", line 18, in <module>
    from cvxpy.atoms.affine.hstack import hstack
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/atoms/affine/hstack.py", line 18, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/cvxcore/python/__init__.py", line 3, in <module>
    import _cvxcore
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_cvxcore.cpython-38-darwin.so, 2): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_cvxcore.cpython-38-darwin.so
  Reason: image not found
```
As one can see, the problem is related to the _cvxcore import.

**Comment by SteveDiamond** [comment]
Have you tried uninstalling cvxpy and reinstalling it?

**Comment by pizquierdo2** [comment]
Yes, and the problem still persists...

**Comment by SteveDiamond** [comment]
Did you install the OS X developer tools?

**Comment by pizquierdo2** [comment]
Sorry, but what do you mean with 'the OS X developer tools'?  (By the way, I'm working over a macOS Catalina 10.15.6).

**Comment by SteveDiamond** [comment]
If you have the Xcode command line tools installed, I don't have any other suggestions. You could try installing through conda. I suspect something is wrong with your Python setup, but I couldn't say what.

**Comment by pizquierdo2** [comment]
Finally I fixed it by adding /usr/lib to rpath using _install_name_tool_. I'll leave the command line here, if someone else needs it:

install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_cvxcore.cpython-38-darwin.so

Thank you for your time.

**Comment by rukawa917** [comment]
May I know what the above command is doing? I can't seem to run the command. Do I have to move **_cvxcore.cpython-38-darwin.so** to somewhere?
