### ISSUE TITLE
TypeError with XPRESS solver

### ISSUE THREAD

**Issue by erelsgl** [cvxpy/cvxpy#1346]
**Describe the bug**
I try to solve a problem with the XPRESS solver (I installed the community edition), but get a TypeError: cannot unpack non-iterable NoneType object.

**To Reproduce**
Here is a minimal example:

	x = cvxpy.Variable()
	problem = cvxpy.Problem(cvxpy.Maximize(x), constraints=[x <= 5])
	problem.solve(solver=cvxpy.XPRESS)  

**Expected behavior**

An optimal solution should be found (5).

**Output**

```
Using the Community license in this session. If you have a full Xpress license, first set the XPAUTH_PATH environment variable to the full path to your license file, xpauth.xpr, and then restart Python. If you want to use the FICO Community license and no longer want to see this message, set the XPAUTH_PATH environment variable to: /usr/local/lib/python3.8/dist-packages/xpress/license/community-xpauth.xpr
NB: setting XPAUTH_PATH will also affect any other Xpress products installed on your system.
Traceback (most recent call last):
  File "/mnt/d/Dropbox/ariel-algorithms/fairpy/indivisible/maximin_share.py", line 150, in <module>
    mms_problem.solve(solver=cvxpy.XPRESS)  
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 395, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 743, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 524, in get_problem_data
    data, inverse_data = solving_chain.apply(self)
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/reductions/chain.py", line 71, in apply
    problem, inv = r.apply(problem)
TypeError: cannot unpack non-iterable NoneType object
```

**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version: 1.1.1

**Comment by erelsgl** [comment]
EDIT: I just upgraded cvxpy to 1.1.12, and the problem is gone.
