### ISSUE TITLE
DCP Error

### ISSUE THREAD

**Issue by QiyaoWei** [cvxpy/cvxpy#1365]
**Describe the bug**
DCP errors occurs with linear objective + quadratic constraint

**To Reproduce**
```
import cvxpy as cvx
import numpy as np

def init_lp_relaxation(A, a, b, sign,
                   v,
                   solver="SCS", sense="max", verbose=True, solve=True, **kwargs):

    _unused = kwargs
    m, n, d = a.shape
    xshape = (n, d)

    x = cvx.Variable(xshape)

    # bounds
    constrs = []
    for i in range(m):
        if sign[i] == 0:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) == b[i]]
        elif sign[i] == -1:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) >= b[i]]
        else:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) <= b[i]]

    # objectives
    obj_expr = cvx.trace(v.reshape(-1,1).T @ x)
    # print(obj_expr)
    obj_expr_cp = cvx.Maximize(obj_expr) if sense == 'max' else cvx.Minimize(
        obj_expr)

    problem = cvx.Problem(objective=obj_expr_cp, constraints=constrs)
    problem.solve(verbose=verbose, solver=solver)


# generate data
n = 80
m = 20
Q = np.random.randint(0, 10, (n, n))
A = np.random.randint(0, 2, (m, n, n))
a = np.random.randint(0, 5, (m, n, 1))
b = np.random.randint(n, 3 * n, (m))
sign = np.ones(shape=m)
lb = np.zeros(shape=(n, 1))
ub = np.ones(shape=(n, 1))

# step 1: compute eigenvalue decomposition of Q
# Note that in QCQP problems we can assume WLOG that Q is symmetric
# Therefore, we operate on symmetric Q and A
Q = Q + Q.T
for i in range(len(A)):
     A[i] = A[i] + A[i].T
w, v = np.linalg.eigh(Q)
# step 2: solve LP for l0 and u0
lb = []
ub = []
for i in range(v.shape[0]):
     low_lp = init_lp_relaxation(A, a, b, sign, v[:, i], solver='MOSEK', sense='min', verbose=True,
                        solve=True)
     up_lp = init_lp_relaxation(A, a, b, sign, v[:, i], solver='MOSEK', sense='max', verbose=True,
                       solve=True)
     lb[i] = low_lp.value
     ub[i] = up_lp.value
```

**Expected behavior**
I expect this program to solve without error

**Output**
```
===============================================================================
                                     CVXPY                                     
                                    v1.1.12                                    
===============================================================================
(CVXPY) May 10 04:11:47 PM: Your problem has 80 variables, 20 constraints, and 0 parameters.
(CVXPY) May 10 04:11:47 PM: It is compliant with the following grammars: 
(CVXPY) May 10 04:11:47 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 10 04:11:47 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
Traceback (most recent call last):
  File "/Users/qiyaowei/qcqp/mwe.py", line 56, in <module>
    low_lp = init_lp_relaxation(A, a, b, sign, np.random.randint(0, 10, (n, 1)), solver='MOSEK', sense='min', verbose=True,
  File "/Users/qiyaowei/qcqp/mwe.py", line 31, in init_lp_relaxation
    problem.solve(verbose=verbose, solver=solver)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 459, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 938, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 565, in get_problem_data
    solving_chain = self._construct_chain(
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 791, in _construct_chain
    return construct_solving_chain(self, candidate_solvers, gp=gp,
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 155, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "/Users/qiyaowei/anaconda3/envs/cur/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 91, in _reductions_for_problem_class
    raise DCPError(
cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The following constraints are not DCP:
0.5 @ QuadForm(var0, [[2. 1. 1. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 1.]
 [2. 1. 2. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]]) + trace([[1. 0. 4. 2. 4. 0. 2. 1. 3. 4. 0. 0. 1. 0. 0. 0. 3. 0. 3. 1. 1. 2. 3. 0.
  2. 3. 0. 1. 1. 3. 2. 4. 4. 0. 1. 3. 3. 2. 4. 2. 1. 0. 2. 1. 3. 3. 0. 3.
  0. 1. 0. 2. 4. 4. 4. 4. 0. 0. 2. 3. 4. 2. 1. 3. 0. 3. 0. 4. 4. 4. 0. 4.
  2. 0. 0. 0. 3. 3. 0. 4.]] @ var0) <= 103.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 1. 1. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 1.]
 [2. 1. 2. ... 1. 2. 1.]
 [1. 2. 1. ... 1. 1. 2.]]) + trace([[1. 0. 4. 2. 4. 0. 2. 1. 3. 4. 0. 0. 1. 0. 0. 0. 3. 0. 3. 1. 1. 2. 3. 0.
  2. 3. 0. 1. 1. 3. 2. 4. 4. 0. 1. 3. 3. 2. 4. 2. 1. 0. 2. 1. 3. 3. 0. 3.
  0. 1. 0. 2. 4. 4. 4. 4. 0. 0. 2. 3. 4. 2. 1. 3. 0. 3. 0. 4. 4. 4. 0. 4.
  2. 0. 0. 0. 3. 3. 0. 4.]] @ var0) <= 103.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 2. 0.]
 [1. 0. 2. ... 0. 2. 1.]
 ...
 [0. 1. 0. ... 2. 0. 1.]
 [1. 2. 2. ... 0. 0. 1.]
 [1. 0. 1. ... 1. 1. 0.]]) + trace([[4. 1. 3. 1. 4. 0. 1. 2. 4. 2. 0. 4. 1. 3. 2. 4. 1. 2. 0. 2. 2. 3. 2. 1.
  0. 3. 3. 4. 2. 1. 0. 3. 0. 1. 4. 3. 1. 1. 1. 2. 4. 4. 1. 0. 3. 4. 3. 3.
  4. 4. 4. 4. 2. 0. 3. 0. 4. 3. 0. 0. 3. 3. 2. 3. 1. 4. 4. 0. 2. 0. 2. 3.
  1. 4. 1. 3. 4. 2. 3. 0.]] @ var0) <= 155.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 2. 0.]
 [1. 0. 2. ... 0. 2. 1.]
 ...
 [0. 1. 0. ... 2. 0. 1.]
 [1. 2. 2. ... 0. 0. 1.]
 [1. 0. 1. ... 1. 1. 0.]]) + trace([[4. 1. 3. 1. 4. 0. 1. 2. 4. 2. 0. 4. 1. 3. 2. 4. 1. 2. 0. 2. 2. 3. 2. 1.
  0. 3. 3. 4. 2. 1. 0. 3. 0. 1. 4. 3. 1. 1. 1. 2. 4. 4. 1. 0. 3. 4. 3. 3.
  4. 4. 4. 4. 2. 0. 3. 0. 4. 3. 0. 0. 3. 3. 2. 3. 1. 4. 4. 0. 2. 0. 2. 3.
  1. 4. 1. 3. 4. 2. 3. 0.]] @ var0) <= 155.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 2. 1. 1.]
 [1. 2. 1. ... 0. 1. 0.]
 [1. 1. 2. ... 2. 1. 1.]
 ...
 [2. 0. 2. ... 0. 1. 2.]
 [1. 1. 1. ... 1. 2. 1.]
 [1. 0. 1. ... 2. 1. 0.]]) + trace([[0. 2. 1. 3. 2. 2. 1. 0. 1. 0. 4. 0. 1. 3. 4. 0. 3. 3. 1. 1. 1. 0. 4. 0.
  1. 2. 4. 2. 0. 1. 1. 3. 3. 4. 3. 2. 2. 3. 4. 4. 1. 3. 1. 4. 3. 1. 1. 4.
  1. 3. 0. 1. 3. 1. 4. 1. 4. 2. 0. 2. 2. 1. 2. 1. 0. 0. 0. 2. 2. 0. 3. 1.
  2. 2. 4. 4. 3. 4. 0. 2.]] @ var0) <= 204.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 2. 1. 1.]
 [1. 2. 1. ... 0. 1. 0.]
 [1. 1. 2. ... 2. 1. 1.]
 ...
 [2. 0. 2. ... 0. 1. 2.]
 [1. 1. 1. ... 1. 2. 1.]
 [1. 0. 1. ... 2. 1. 0.]]) + trace([[0. 2. 1. 3. 2. 2. 1. 0. 1. 0. 4. 0. 1. 3. 4. 0. 3. 3. 1. 1. 1. 0. 4. 0.
  1. 2. 4. 2. 0. 1. 1. 3. 3. 4. 3. 2. 2. 3. 4. 4. 1. 3. 1. 4. 3. 1. 1. 4.
  1. 3. 0. 1. 3. 1. 4. 1. 4. 2. 0. 2. 2. 1. 2. 1. 0. 0. 0. 2. 2. 0. 3. 1.
  2. 2. 4. 4. 3. 4. 0. 2.]] @ var0) <= 204.0
0.5 @ QuadForm(var0, [[2. 0. 2. ... 2. 0. 0.]
 [0. 2. 1. ... 1. 0. 1.]
 [2. 1. 2. ... 1. 0. 1.]
 ...
 [2. 1. 1. ... 2. 2. 0.]
 [0. 0. 0. ... 2. 0. 1.]
 [0. 1. 1. ... 0. 1. 0.]]) + trace([[1. 4. 0. 1. 0. 1. 0. 3. 4. 3. 4. 4. 0. 3. 2. 2. 3. 4. 1. 0. 2. 3. 4. 0.
  4. 4. 3. 3. 4. 1. 4. 4. 0. 2. 4. 4. 3. 4. 0. 4. 2. 3. 0. 0. 0. 3. 3. 3.
  3. 0. 3. 3. 0. 0. 4. 0. 3. 4. 2. 3. 3. 3. 2. 0. 4. 0. 1. 0. 3. 0. 1. 0.
  4. 4. 2. 0. 1. 2. 1. 4.]] @ var0) <= 236.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 0. 2. ... 2. 0. 0.]
 [0. 2. 1. ... 1. 0. 1.]
 [2. 1. 2. ... 1. 0. 1.]
 ...
 [2. 1. 1. ... 2. 2. 0.]
 [0. 0. 0. ... 2. 0. 1.]
 [0. 1. 1. ... 0. 1. 0.]]) + trace([[1. 4. 0. 1. 0. 1. 0. 3. 4. 3. 4. 4. 0. 3. 2. 2. 3. 4. 1. 0. 2. 3. 4. 0.
  4. 4. 3. 3. 4. 1. 4. 4. 0. 2. 4. 4. 3. 4. 0. 4. 2. 3. 0. 0. 0. 3. 3. 3.
  3. 0. 3. 3. 0. 0. 4. 0. 3. 4. 2. 3. 3. 3. 2. 0. 4. 0. 1. 0. 3. 0. 1. 0.
  4. 4. 2. 0. 1. 2. 1. 4.]] @ var0) <= 236.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 1. 2. 2.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 2. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [2. 1. 1. ... 0. 2. 1.]
 [2. 0. 1. ... 0. 1. 2.]]) + trace([[0. 0. 1. 0. 2. 2. 0. 0. 2. 3. 0. 4. 1. 2. 1. 2. 2. 1. 3. 4. 4. 1. 1. 4.
  4. 1. 2. 1. 4. 2. 4. 0. 3. 1. 2. 4. 0. 3. 3. 1. 1. 1. 1. 3. 2. 2. 3. 2.
  4. 1. 2. 0. 3. 1. 4. 3. 0. 4. 4. 2. 3. 4. 4. 2. 4. 4. 0. 4. 2. 3. 1. 3.
  1. 3. 1. 1. 0. 3. 4. 2.]] @ var0) <= 205.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 1. 2. 2.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 2. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [2. 1. 1. ... 0. 2. 1.]
 [2. 0. 1. ... 0. 1. 2.]]) + trace([[0. 0. 1. 0. 2. 2. 0. 0. 2. 3. 0. 4. 1. 2. 1. 2. 2. 1. 3. 4. 4. 1. 1. 4.
  4. 1. 2. 1. 4. 2. 4. 0. 3. 1. 2. 4. 0. 3. 3. 1. 1. 1. 1. 3. 2. 2. 3. 2.
  4. 1. 2. 0. 3. 1. 4. 3. 0. 4. 4. 2. 3. 4. 4. 2. 4. 4. 0. 4. 2. 3. 1. 3.
  1. 3. 1. 1. 0. 3. 4. 2.]] @ var0) <= 205.0
0.5 @ QuadForm(var0, [[2. 2. 0. ... 2. 1. 0.]
 [2. 0. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 1. 2. 2.]
 ...
 [2. 0. 1. ... 0. 2. 1.]
 [1. 1. 2. ... 2. 0. 1.]
 [0. 0. 2. ... 1. 1. 2.]]) + trace([[1. 2. 4. 4. 1. 4. 0. 3. 3. 1. 2. 4. 2. 1. 4. 1. 4. 0. 3. 2. 4. 0. 3. 0.
  2. 4. 3. 3. 4. 0. 0. 0. 1. 3. 0. 0. 2. 2. 2. 3. 0. 2. 0. 4. 2. 0. 4. 3.
  0. 2. 0. 4. 0. 0. 0. 3. 1. 3. 3. 4. 4. 1. 3. 2. 3. 0. 1. 2. 3. 0. 0. 0.
  3. 4. 4. 4. 2. 1. 1. 2.]] @ var0) <= 226.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 2. 0. ... 2. 1. 0.]
 [2. 0. 2. ... 0. 1. 0.]
 [0. 2. 2. ... 1. 2. 2.]
 ...
 [2. 0. 1. ... 0. 2. 1.]
 [1. 1. 2. ... 2. 0. 1.]
 [0. 0. 2. ... 1. 1. 2.]]) + trace([[1. 2. 4. 4. 1. 4. 0. 3. 3. 1. 2. 4. 2. 1. 4. 1. 4. 0. 3. 2. 4. 0. 3. 0.
  2. 4. 3. 3. 4. 0. 0. 0. 1. 3. 0. 0. 2. 2. 2. 3. 0. 2. 0. 4. 2. 0. 4. 3.
  0. 2. 0. 4. 0. 0. 0. 3. 1. 3. 3. 4. 4. 1. 3. 2. 3. 0. 1. 2. 3. 0. 0. 0.
  3. 4. 4. 4. 2. 1. 1. 2.]] @ var0) <= 226.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 2.]
 [1. 2. 0. ... 0. 1. 0.]
 [1. 0. 2. ... 1. 2. 1.]
 ...
 [0. 0. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 0.]
 [2. 0. 1. ... 2. 0. 0.]]) + trace([[1. 4. 2. 3. 3. 1. 1. 4. 0. 2. 0. 4. 1. 3. 0. 3. 4. 0. 4. 1. 3. 4. 1. 2.
  3. 4. 3. 3. 4. 3. 1. 1. 1. 2. 0. 0. 3. 3. 3. 3. 1. 2. 2. 4. 4. 1. 1. 3.
  3. 3. 0. 3. 1. 3. 2. 2. 1. 0. 3. 2. 1. 0. 2. 0. 3. 0. 0. 0. 2. 4. 3. 0.
  4. 1. 0. 4. 1. 3. 0. 4.]] @ var0) <= 183.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 2.]
 [1. 2. 0. ... 0. 1. 0.]
 [1. 0. 2. ... 1. 2. 1.]
 ...
 [0. 0. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 0.]
 [2. 0. 1. ... 2. 0. 0.]]) + trace([[1. 4. 2. 3. 3. 1. 1. 4. 0. 2. 0. 4. 1. 3. 0. 3. 4. 0. 4. 1. 3. 4. 1. 2.
  3. 4. 3. 3. 4. 3. 1. 1. 1. 2. 0. 0. 3. 3. 3. 3. 1. 2. 2. 4. 4. 1. 1. 3.
  3. 3. 0. 3. 1. 3. 2. 2. 1. 0. 3. 2. 1. 0. 2. 0. 3. 0. 0. 0. 2. 4. 3. 0.
  4. 1. 0. 4. 1. 3. 0. 4.]] @ var0) <= 183.0
0.5 @ QuadForm(var0, [[0. 2. 2. ... 0. 2. 1.]
 [2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 0. 1.]
 ...
 [0. 1. 1. ... 2. 1. 1.]
 [2. 2. 0. ... 1. 2. 0.]
 [1. 0. 1. ... 1. 0. 2.]]) + trace([[3. 0. 4. 0. 4. 3. 3. 1. 2. 1. 4. 1. 0. 1. 4. 3. 4. 4. 3. 3. 2. 0. 2. 4.
  4. 3. 3. 2. 1. 2. 1. 2. 2. 2. 2. 2. 4. 4. 2. 1. 4. 2. 2. 0. 1. 0. 1. 3.
  1. 0. 2. 1. 4. 2. 4. 0. 4. 2. 0. 3. 1. 1. 2. 4. 4. 1. 0. 2. 4. 3. 2. 3.
  3. 0. 4. 4. 0. 4. 0. 4.]] @ var0) <= 191.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 2. 2. ... 0. 2. 1.]
 [2. 0. 0. ... 1. 2. 0.]
 [2. 0. 0. ... 1. 0. 1.]
 ...
 [0. 1. 1. ... 2. 1. 1.]
 [2. 2. 0. ... 1. 2. 0.]
 [1. 0. 1. ... 1. 0. 2.]]) + trace([[3. 0. 4. 0. 4. 3. 3. 1. 2. 1. 4. 1. 0. 1. 4. 3. 4. 4. 3. 3. 2. 0. 2. 4.
  4. 3. 3. 2. 1. 2. 1. 2. 2. 2. 2. 2. 4. 4. 2. 1. 4. 2. 2. 0. 1. 0. 1. 3.
  1. 0. 2. 1. 4. 2. 4. 0. 4. 2. 0. 3. 1. 1. 2. 4. 4. 1. 0. 2. 4. 3. 2. 3.
  3. 0. 4. 4. 0. 4. 0. 4.]] @ var0) <= 191.0
0.5 @ QuadForm(var0, [[0. 2. 1. ... 1. 1. 1.]
 [2. 2. 1. ... 1. 2. 0.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 0.]
 [1. 2. 2. ... 1. 2. 0.]
 [1. 0. 1. ... 0. 0. 2.]]) + trace([[3. 0. 3. 3. 3. 1. 1. 3. 4. 2. 0. 0. 0. 4. 3. 0. 3. 0. 1. 1. 4. 0. 3. 4.
  3. 0. 2. 1. 4. 1. 2. 4. 0. 3. 4. 1. 1. 4. 4. 4. 4. 2. 2. 2. 2. 0. 1. 1.
  2. 2. 2. 4. 1. 4. 0. 0. 2. 4. 4. 0. 4. 3. 3. 2. 0. 1. 2. 0. 1. 3. 3. 0.
  4. 4. 0. 1. 4. 4. 3. 3.]] @ var0) <= 134.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 2. 1. ... 1. 1. 1.]
 [2. 2. 1. ... 1. 2. 0.]
 [1. 1. 2. ... 0. 2. 1.]
 ...
 [1. 1. 0. ... 2. 1. 0.]
 [1. 2. 2. ... 1. 2. 0.]
 [1. 0. 1. ... 0. 0. 2.]]) + trace([[3. 0. 3. 3. 3. 1. 1. 3. 4. 2. 0. 0. 0. 4. 3. 0. 3. 0. 1. 1. 4. 0. 3. 4.
  3. 0. 2. 1. 4. 1. 2. 4. 0. 3. 4. 1. 1. 4. 4. 4. 4. 2. 2. 2. 2. 0. 1. 1.
  2. 2. 2. 4. 1. 4. 0. 0. 2. 4. 4. 0. 4. 3. 3. 2. 0. 1. 2. 0. 1. 3. 3. 0.
  4. 4. 0. 1. 4. 4. 3. 3.]] @ var0) <= 134.0
0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 0.]
 [1. 2. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 2.]
 ...
 [0. 2. 1. ... 2. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [0. 2. 2. ... 1. 1. 2.]]) + trace([[4. 2. 0. 4. 4. 2. 3. 4. 1. 3. 4. 4. 4. 2. 0. 0. 4. 3. 2. 0. 1. 1. 1. 1.
  3. 2. 0. 3. 4. 3. 4. 1. 3. 0. 2. 0. 2. 3. 4. 1. 2. 1. 4. 0. 2. 4. 2. 0.
  3. 1. 3. 0. 4. 0. 1. 4. 1. 1. 4. 0. 3. 2. 0. 0. 2. 1. 1. 0. 1. 1. 3. 3.
  2. 1. 1. 1. 2. 2. 2. 1.]] @ var0) <= 169.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 1. ... 0. 1. 0.]
 [1. 2. 1. ... 2. 1. 2.]
 [1. 1. 2. ... 1. 0. 2.]
 ...
 [0. 2. 1. ... 2. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [0. 2. 2. ... 1. 1. 2.]]) + trace([[4. 2. 0. 4. 4. 2. 3. 4. 1. 3. 4. 4. 4. 2. 0. 0. 4. 3. 2. 0. 1. 1. 1. 1.
  3. 2. 0. 3. 4. 3. 4. 1. 3. 0. 2. 0. 2. 3. 4. 1. 2. 1. 4. 0. 2. 4. 2. 0.
  3. 1. 3. 0. 4. 0. 1. 4. 1. 1. 4. 0. 3. 2. 0. 0. 2. 1. 1. 0. 1. 1. 3. 3.
  2. 1. 1. 1. 2. 2. 2. 1.]] @ var0) <= 169.0
0.5 @ QuadForm(var0, [[0. 1. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 1. 2. 0.]
 [0. 1. 2. ... 1. 1. 1.]
 ...
 [0. 1. 1. ... 2. 2. 0.]
 [1. 2. 1. ... 2. 2. 1.]
 [1. 0. 1. ... 0. 1. 0.]]) + trace([[1. 4. 1. 3. 3. 3. 0. 2. 4. 2. 4. 3. 1. 0. 4. 0. 1. 3. 2. 2. 4. 2. 0. 0.
  1. 0. 0. 2. 2. 1. 2. 2. 0. 3. 1. 0. 3. 4. 2. 0. 2. 3. 1. 3. 1. 2. 3. 2.
  2. 2. 2. 4. 2. 0. 3. 4. 1. 0. 1. 1. 0. 0. 4. 2. 0. 0. 3. 0. 4. 3. 0. 4.
  3. 1. 0. 4. 4. 3. 1. 0.]] @ var0) <= 222.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[0. 1. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 1. 2. 0.]
 [0. 1. 2. ... 1. 1. 1.]
 ...
 [0. 1. 1. ... 2. 2. 0.]
 [1. 2. 1. ... 2. 2. 1.]
 [1. 0. 1. ... 0. 1. 0.]]) + trace([[1. 4. 1. 3. 3. 3. 0. 2. 4. 2. 4. 3. 1. 0. 4. 0. 1. 3. 2. 2. 4. 2. 0. 0.
  1. 0. 0. 2. 2. 1. 2. 2. 0. 3. 1. 0. 3. 4. 2. 0. 2. 3. 1. 3. 1. 2. 3. 2.
  2. 2. 2. 4. 2. 0. 3. 4. 1. 0. 1. 1. 0. 0. 4. 2. 0. 0. 3. 0. 4. 3. 0. 4.
  3. 1. 0. 4. 4. 3. 1. 0.]] @ var0) <= 222.0
0.5 @ QuadForm(var0, [[2. 1. 1. ... 2. 2. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 0. 1. 1.]
 ...
 [2. 1. 0. ... 2. 1. 1.]
 [2. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 2.]]) + trace([[1. 1. 0. 3. 3. 2. 3. 4. 4. 4. 1. 1. 2. 4. 2. 1. 2. 0. 3. 3. 2. 1. 3. 3.
  3. 0. 4. 0. 2. 0. 3. 1. 4. 0. 4. 0. 1. 4. 1. 2. 2. 1. 3. 3. 3. 0. 3. 3.
  1. 2. 3. 3. 4. 0. 4. 3. 2. 4. 0. 2. 0. 2. 4. 0. 4. 4. 4. 1. 0. 1. 3. 0.
  2. 1. 2. 0. 0. 2. 2. 4.]] @ var0) <= 178.0 , because the following subexpressions are not:
|--  0.5 @ QuadForm(var0, [[2. 1. 1. ... 2. 2. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 0. 1. 1.]
 ...
 [2. 1. 0. ... 2. 1. 1.]
 [2. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 2.]]) + trace([[1. 1. 0. 3. 3. 2. 3. 4. 4. 4. 1. 1. 2. 4. 2. 1. 2. 0. 3. 3. 2. 1. 3. 3.
  3. 0. 4. 0. 2. 0. 3. 1. 4. 0. 4. 0. 1. 4. 1. 2. 2. 1. 3. 3. 3. 0. 3. 3.
  1. 2. 3. 3. 4. 0. 4. 3. 2. 4. 0. 2. 0. 2. 4. 0. 4. 4. 4. 1. 0. 1. 3. 0.
  2. 1. 2. 0. 0. 2. 2. 4.]] @ var0) <= 178.0

Process finished with exit code 1
```

**Version**
 - OS: Mac 11.2.3
 - CVXPY Version: 1.1.12

**Additional context**
This is part of my attempt to relax a QP problem using Q's eigenvalue, hence the eigenvalue part at the beginning of the code. However, I tested this code with random generated arrays and the same errors persisted. Therefore, I don't think it's a problem with the input. I am confused because I believe Quadform should be DCP compatible. Any help would be appreciated!

P.S. I have made multiple edits for better formatting. Nothing important

**Comment by SteveDiamond** [comment]
I'm not really sure what's goin on here:
```
    for i in range(m):
        if sign[i] == 0:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) == b[i]]
        elif sign[i] == -1:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) >= b[i]]
        else:
            constrs += [(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) <= b[i]]
```
but this is almost certainly not DCP. The DCP usage of ``quad_form`` is ``(1/2) * cvx.quad_form(x, A[i]) + cvx.trace(a[i].T @ x) <= b[i]`` when ``A[i]`` is positive semidefinite.

**Comment by QiyaoWei** [comment]
Thanks a lot for your quick reply! A[i] not being PSD was indeed the problem. As a follow-up, what should I use (to arrive at the same expression) in the case of A[i] only being symmetric?

**Comment by SteveDiamond** [comment]
I'm not really sure what you mean. The only time ``cvx.quad_form(x, A[i])`` is convex is when ``A[i]`` is symmetric positive semidefinite. Otherwise it's not convex and you can't use it in cvxpy.
