### ISSUE TITLE
"candidate QP/Conic solvers ([]) are not MIP-capable" for linear problem

### ISSUE THREAD

**Issue by mdavis-xyz** [cvxpy/cvxpy#1387]
**Describe the bug**

I'm trying to solve a linear problem using [this style](https://yetanothermathprogrammingconsultant.blogspot.com/2008/05/multiplication-of-continuous-and-binary.html) of big-M trick and cvxopt.

**To Reproduce**

`Dockerfile` to install dependencies in a clean slate:

```
FROM lambci/lambda:build-python3.8
RUN yum update -y
RUN yum upgrade -y
RUN yum install wget -y
# https://www.cvxpy.org/install/index.html#install-with-cvxopt-and-glpk-support

# install glpk
RUN gpg --keyserver keys.gnupg.net --recv-keys 5981E818
RUN wget https://ftp.gnu.org/gnu/glpk/glpk-5.0.tar.gz
RUN wget https://ftp.gnu.org/gnu/glpk/glpk-5.0.tar.gz.sig
RUN gpg --verify glpk-5.0.tar.gz.sig
RUN tar -xzf glpk-5.0.tar.gz
WORKDIR glpk-5.0

ENV GLPK_BUILD_PREFIX=/glpk
ENV CVXOPT_BUILD_GLPK=1
ENV CVXOPT_GLPK_LIB_DIR=$GLPK_BUILD_PREFIX/lib
ENV CVXOPT_GLPK_INC_DIR=$GLPK_BUILD_PREFIX/include
RUN ./configure --disable-shared --prefix=$GLPK_BUILD_PREFIX
RUN make
RUN make check
RUN make install

RUN pip install cvxopt
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY test.py ./
RUN python test.py CVXOPT
```

`requirements.txt`
```
cvxpy 
numpy>=1.15 
scipy>=1.1.0
```

`test.py`
```
import cvxpy as cp
from sys import argv

# Create two scalar optimization variables.
z = cp.Variable()
x = cp.Variable()
x_lo, x_up = (-10, 10)
d = cp.Variable(integer=True)

constraints = [
    x_lo <= x,
    x <= x_up,
    min(0, x_lo) <= z,
    z <= max(0, x_up),
    x_lo * d <= z,
    z <= x_up * d,
    x - x_up * (1-d) <= z,
    z <= x - x_lo * (1 - d)
]

# Form objective.
obj = cp.Minimize(z + x + d)

# Form and solve problem.
prob = cp.Problem(obj, constraints)
try:
    solver = argv[1]
    print(f"Using {solver}")
except IndexError:
    print("Using default solver")
    prob.solve()
else:
    prob.solve(solver=getattr(cp, solver))
    
print("status:", prob.status)
print("optimal value", prob.value)
print(f"optimal var {x.value=} {d.value=} {z.value=}")
assert prob.status == 'optimal'
```

Run with `docker build .`

**Expected behavior**

The docker build is sucessful.
Python ran the problem and solved it optimally with CVXOPT.

**Output**

```
 > [cvxopt 16/16] RUN python test.py CVXOPT:
#23 2.391 Using CVXOPT
#23 2.395 Traceback (most recent call last):
#23 2.395   File "test.py", line 33, in <module>
#23 2.395     prob.solve(solver=getattr(cp, solver))
#23 2.395   File "/var/lang/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 459, in solve
#23 2.395     return solve_func(self, *args, **kwargs)
#23 2.395   File "/var/lang/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 938, in _solve
#23 2.395     data, solving_chain, inverse_data = self.get_problem_data(
#23 2.395   File "/var/lang/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 565, in get_problem_data
#23 2.395     solving_chain = self._construct_chain(
#23 2.395   File "/var/lang/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 789, in _construct_chain
#23 2.395     candidate_solvers = self._find_candidate_solvers(solver=solver, gp=gp)
#23 2.395   File "/var/lang/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 723, in _find_candidate_solvers
#23 2.395     raise error.SolverError(
#23 2.395 cvxpy.error.SolverError: Problem is mixed-integer, but candidate QP/Conic solvers ([]) are not MIP-capable.
```

Note that I did not tell cvxpy to use a QP/Conic solver. It infered that from the problem, I think.
I believe this problem is linear.

**Version**
 - OS: Amazon Linux
 - CVXPY Version: 1.1.12

**Additional context**

**Comment by mdavis-xyz** [comment]
Ah nevermind, the problem is that CVXOPT doesn't handle MIP, not that the problem is itself QP/Conic.
It's a misleading error message, that's all.
