### ISSUE TITLE
error when using indicator transform

### ISSUE THREAD

**Issue by michael-123123** [cvxpy/cvxpy#1394]
**Describe the bug**
There is an error when the indicator transform is used in conjunction with Minimize goal.

**To Reproduce**
```
>>> from cvxpy import *
>>> a = Variable ()
>>> b = Variable ()
>>> c = cvxpy.transforms.indicator([a+b == 5])
>>> o = Minimize (0)
>>> p = Problem(o, [c <= 0])
>>> p.solve ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 401, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 818, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 140, in solve_via_data
    **solver_opts)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
RuntimeError: Internal problem occurred in ECOS while setting up the problem.
Please send a bug report with data to Alexander Domahidi.
Email: domahidi@control.ee.ethz.ch
```

**Expected behavior**
```
>>> from cvxpy import *
>>> a = Variable ()
>>> b = Variable ()
>>> c = cvxpy.transforms.indicator([a+b == 5])
>>> o = Minimize (0)
>>> p = Problem(o, [c <= 0])
>>> p.solve ()
-0.0
>>> p.status
optimal
>>> a.value
2.5
>> b.value
2.5
```

**Output**
```
>>> from cvxpy import *
>>> a = Variable ()
>>> b = Variable ()
>>> c = cvxpy.transforms.indicator([a+b == 5])
>>> o = Minimize (0)
>>> p = Problem(o, [c <= 0])
>>> p.solve ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 401, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 818, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 341, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 140, in solve_via_data
    **solver_opts)
  File "/home/user/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
RuntimeError: Internal problem occurred in ECOS while setting up the problem.
Please send a bug report with data to Alexander Domahidi.
Email: domahidi@control.ee.ethz.ch
```
**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version:1.1.11

**Additional context**

**Comment by SteveDiamond** [comment]
It works fine for me. Maybe try the latest cvxpy?

**Comment by SteveDiamond** [comment]
Someone else will need to try this then, since your code runs for me without error.

**Comment by michael-123123** [comment]
ok. thanks.

**Comment by phschiele** [comment]
I was able to reproduce the error on my side w/ latest master. It does work with other solvers, though.

**Comment by SteveDiamond** [comment]
Ok since this is an ECOS problem not a cvxpy problem I'm moving the issue to the ECOS repo: https://github.com/embotech/ecos/issues/199
