### ISSUE TITLE
ARPACK error 3 while solving the quadratic program

### ISSUE THREAD

**Issue by sandeepparameshwara** [cvxpy/cvxpy#1421]
Hello,

I am solving a QP using OSQP. The QP is solved at a particular time instance, but I get this error immediately

```
Traceback (most recent call last):
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 243, in extremal_eig_near_ref
    ev = SA_eigsh(sigma)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 238, in SA_eigsh
    return eigsh(A, k=1, sigma=sigma, return_eigenvectors=False)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1687, in eigsh
    params.iterate()
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 573, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/controller_mpc_et.py", line 444, in <module>
    main()
  File "e:/controller_mpc_et.py", line 385, in main
    x2,u2,u2_full,x20,cost2,time2,total_cost2,counter2,et_triggers2 = solve_linear_mpc1(state2,ref_traj2[j:j+N+1,:],drone2,Ad,Bd,x_hat,tim,G[1,:],formation_dis[1,:],x_hat[1],gammma,S,Q_hat,R_hat,I_m, u_m, gama_z, z_m,drone2_input,cost2,counter2,drone2_states,et_triggers2)
  File "e:/controller_mpc_et.py", line 140, in solve_linear_mpc1
    problem.solve(verbose=True,solver='OSQP')
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 751, in _solve
    solver, gp, enforce_dpp)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 500, in get_problem_data
    solver=solver, gp=gp, enforce_dpp=enforce_dpp)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 659, in _construct_chain
    enforce_dpp=enforce_dpp)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 151, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 81, in _reductions_for_problem_class
    if not gp and not problem.is_dcp():
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\utilities\performance_utils.py", line 70, in _compute_once
    result = func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 166, in is_dcp
    expr.is_dcp(dpp) for expr in self.constraints + [self.objective])
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 166, in <genexpr>
    expr.is_dcp(dpp) for expr in self.constraints + [self.objective])
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\problems\objective.py", line 151, in is_dcp
    return self.args[0].is_convex()
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\utilities\performance_utils.py", line 70, in _compute_once
    result = func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\atoms\atom.py", line 173, in is_convex
    if not (arg.is_affine() or
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\utilities\performance_utils.py", line 70, in _compute_once
    result = func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\expression.py", line 177, in is_affine
    return self.is_constant() or (self.is_convex() and self.is_concave())
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\utilities\performance_utils.py", line 70, in _compute_once
    result = func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\atoms\atom.py", line 171, in is_convex
    elif self.is_atom_convex():
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\atoms\quad_form.py", line 64, in is_atom_convex
    return P.is_constant() and P.is_psd()
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\utilities\performance_utils.py", line 70, in _compute_once
    result = func(self, *args, **kwargs)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 206, in is_psd
    ev = extremal_eig_near_ref(self.value, EIGVAL_TOL, low=True)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 247, in extremal_eig_near_ref
    ev = SA_eigsh(sigma)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 238, in SA_eigsh
    return eigsh(A, k=1, sigma=sigma, return_eigenvectors=False)
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1687, in eigsh
    params.iterate()
  File "C:\Users\SPA18\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 573, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV.
```
I inspected the output of the previous optimization. Nothing looks strange. The optimal value also seems to be correct. Nothing abrupt is happening, the simulation is also right up to this time instance, so I suspect this is purely a solver issue. Could anyone please point out what's happening? I believe this problem is coming from OSQP.

**Version**
 - OS: Windows 10
 -  OSQP v0.6.2
 - CVXPY Version: 1.1.7

Thank you
Sandeep

**Comment by sandeepparameshwara** [comment]
Hi, any help or suggestion would be really helpful

**Comment by sandeepparameshwara** [comment]
It is solved by using `psd_wrap(P)` as suggested in https://github.com/cvxpy/cvxpy/issues/1424#issuecomment-864504483 where P is covariance matrix in the objective function.
