### ISSUE TITLE
Call to CVXOPT crashes without any informative error

### ISSUE THREAD

**Issue by croci** [cvxpy/cvxpy#1588]
**Describe the bug**
Calling CVXOPT with a badly scaled SDP causes CVXPY to crash without any information.

**To Reproduce**
See minimum working code and data in the attached zip file. The matrix psi is badly scaled. Setting scale to 1 causes the solver to crash. A better scaling makes it work.
[crash.zip](https://github.com/cvxpy/cvxpy/files/7759138/crash.zip)

**Expected behavior**
It would be useful to have more indication as to why CVXOPT failed.

**Output**
```bash
===============================================================================
                                     CVXPY                                     
                                    v1.1.17                                    
===============================================================================
(CVXPY) Dec 21 06:46:23 PM: Your problem has 64 variables, 3 constraints, and 0 parameters.
(CVXPY) Dec 21 06:46:23 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Dec 21 06:46:23 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Dec 21 06:46:23 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Dec 21 06:46:23 PM: Compiling problem (target solver=CVXOPT).
(CVXPY) Dec 21 06:46:23 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> CVXOPT
(CVXPY) Dec 21 06:46:23 PM: Applying reduction Dcp2Cone
(CVXPY) Dec 21 06:46:23 PM: Applying reduction CvxAttr2Constr
(CVXPY) Dec 21 06:46:23 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Dec 21 06:46:23 PM: Applying reduction CVXOPT
(CVXPY) Dec 21 06:46:23 PM: Finished problem compilation (took 8.705e-03 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Dec 21 06:46:23 PM: Invoking solver CVXOPT  to obtain a solution.
Traceback (most recent call last):
  File "crash.py", line 31, in <module>
    problem.solve(verbose=True, solver="CVXOPT", abstol=1.0e-13, reltol=1.e-6, max_iters=200, feastol=1.0e-6, kttsolver='chol',refinement=2)
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 472, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 978, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/usr/local/lib/python3.8/dist-packages/cvxpy/problems/problem.py", line 1300, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'CVXOPT' failed. Try another solver, or solve with verbose=True for more information.

```

**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version: 1.1.17

**Additional context**
In general I found CVXOPT to be extremely sensitive to scaling.

**Comment by rileyjmurray** [comment]
Hi @croci, sorry for taking so long to get back to you. We appreciate you submitting the test problem here. I think it's reasonable for cvxpy to print CVXOPT's internal error message as part of raising the solver failure. I'll leave this issue open until we make that change. I'll also link this issue to #1205 for us to consider in the future.

**Comment by croci** [comment]
Thanks @rileyjmurray . Would it also be possible to have CVXOPT return the current best found solution and/or the last iterate even upon failure and/or when maxit is reached?

I find that for badly scaled KKT systems CVXOPT often manages to find the optimal solution, yet it fails to report convergence and keeps idly iterating before crashing with an error. When this happens the solution/last iterate is completelly lost at the moment.

This is possibly related to #1548 . I can create a separate issue if you prefer.

**Comment by croci** [comment]
Any news on this?

**Comment by chofchof** [comment]
One simple way to catch the CVXOPT error message is to modify `cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py` (line 200) as follows.
```
        try:
            results_dict = cvxopt.solvers.conelp(c, G, h, dims, A, b,
                                                 kktsolver=kktsolver)
        # Catch exceptions in CVXOPT and convert them to solver errors.
        except ValueError as e:
            print(e)
            results_dict = {"status": "unknown"}
```
@croci's `crash.py` raised the ValueError message `Rank(A) < p or Rank([G; A]) < n` as @GrahamHulsey's issue #2417.

**Comment by SteveDiamond** [comment]
This change sounds reasonable. I don't see much reason to use cvxopt at this point but of course we would like all our interfaces to be as nice as possible.

**Comment by croci** [comment]
What is now the recommended solver for SDPs? CLARABEL?

**Comment by rileyjmurray** [comment]
Yes, Clarabel is now our recommended SDP solver.
