### ISSUE TITLE
Wrong curvature for matrix_frac?

### ISSUE THREAD

**Issue by julien-klaus** [cvxpy/cvxpy#1597]
There are some issues with the `matrix_frac` atomic function. It calculates **x' Px** for some vector **x** and matrix **P**. The curvature depends on the the definitness of **P**. 

**To Reproduce** (I use the following versions)
 - OS: Microsoft Windows 10 Education (Version 10.0.19042 Build 19042)
 - CVXPY Version: 1.1.18
 - Anaconda Version: 4.11.0
 - Python Version: 3.8.12

There are two different problems. There is a false curvature detected for the following code snipped.
````
n = 2
x = cp.Variable(n)
P = cp.Parameter((n, n), NSD=True)

cost = cp.matrix_frac(x, P)
print(cost.curvature) # should be concave, but returns convex
````
So I think there is something missing. The following code snipped gives further hints about it.

````
# create some variables and parameter
n = 2
x = cp.Variable(n)
P = cp.Parameter((n, n), PSD=True)
P.value = np.eye(n)

# define an objective with matrix_frac
cost = cp.matrix_frac(x, P)
obj = cp.Minimize(cost)
problem = cp.Problem(obj)

# solving crashes
x = problem.solve()
````

I expect the latter code to solve the convex problem for variable **x**. Instead it cashes with

````
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\utilities\performance_utils.py", line 37, in _lazyprop
    return getattr(self, attr_name)
AttributeError: 'MatrixFrac' object has no attribute '_lazy_canonical_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Julien Klaus/AppData/Roaming/JetBrains/PyCharm2021.2/scratches/cvx_scratch.py", line 19, in <module>
    x = problem.solve()
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\problems\problem.py", line 473, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\problems\problem.py", line 966, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\problems\problem.py", line 627, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\reductions\chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\reductions\qp2quad_form\qp_matrix_stuffing.py", line 261, in apply
    params_to_P, params_to_q, flattened_variable = self.stuffed_objective(
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\reductions\qp2quad_form\qp_matrix_stuffing.py", line 246, in stuffed_objective
    params_to_P, params_to_q = extractor.quad_form(expr)
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 195, in quad_form
    coeffs, constant = self.extract_quadratic_coeffs(root.args[0],
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 105, in extract_quadratic_coeffs
    op_list = [affine_expr.canonical_form[0]]
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\utilities\performance_utils.py", line 39, in _lazyprop
    setattr(self, attr_name, func(self))
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\utilities\canonical.py", line 43, in canonical_form
    return self.canonicalize()
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\atoms\atom.py", line 327, in canonicalize
    graph_obj, graph_constr = self.graph_implementation(arg_objs,
  File "C:\ProgramData\Anaconda3\envs\scratches\lib\site-packages\cvxpy\atoms\atom.py", line 351, in graph_implementation
    raise NotImplementedError()
NotImplementedError
````

**Comment by keithbriggs** [comment]
I thought `matrix_frac` computed **tr X.T*P^-1*X**?

**Comment by julien-klaus** [comment]
> I thought `matrix_frac` computed **tr X.T_P^-1_X**?

Thank you for the reply. You are right, I forgot the inverse. But I could not found the trace in the scalar function table of https://www.cvxpy.org/tutorial/functions/index.html , but at the https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#matrix-frac it is the way you told. 

Nevertheless the inverse does not change the curvature. I have no clue if the trace does so. Is this table may outdated?

**Comment by keithbriggs** [comment]
Trace is in the table:

`trace(X) | tr(X) ...`

**Comment by julien-klaus** [comment]
I mean in the definition of `matrix_frac` in the table. Okay. So trace is affine and should not change the curvature. 
So applying the new knowledge `matrix_frac(X, A) = tr(X'*A*X)` if I calculate the second derivative of it I get A'+A. So the curvature depends on the definitness of A if A is positiv semidefinit the curvature if `matrix_frac` should be convex and if A is nsd it should be concave. But this is somehow not the case, if I did everything correct in the first code snipped above.

**Comment by keithbriggs** [comment]
In your examples, the quadratic form is a scalar so the trace should do nothing.   I see in the source code that trace is taken in some circumstances, but I don't know why.    We need the experts - wait a couple of hours for west coast US to wake up!

**Comment by SteveDiamond** [comment]
@julien-klaus it looks like the logic for ``matrix_frac(x, P)`` where ``P`` is a parameter is not correctly fleshed out. But it should be fine when ``P`` is not a parameter, and of course if ``P`` is a parameter you can use ``quad_form``.

**Comment by julien-klaus** [comment]
@SteveDiamond thank you for the answer. I just came across it doing some experiments, and was more interested if this is a bug, so somebody can fix it. Thank you both.
