### ISSUE TITLE
Boolean Variable With No Constraints raises TypeError: G must be a 'd' matrix

### ISSUE THREAD

**Issue by bqi343** [cvxpy/cvxpy#1614]
**Describe the bug**

I am trying to solve a mixed-integer program after installing CVXOPT as mentioned [here](https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs). The following code snippet results in an error:

```py
import cvxpy as cp

x = cp.Variable(boolean=True)
obj = cp.Maximize(0.23 * x)
prob = cp.Problem(obj)
print(prob.solve(solver="GLPK_MI", verbose=True))
```

It runs without error when I add a constraint though:

```py
import cvxpy as cp

x = cp.Variable(boolean=True)
obj = cp.Maximize(0.23 * x)
prob = cp.Problem(obj, [x >= 0])
print(prob.solve(solver="GLPK_MI", verbose=True))
```

**Expected behavior**
The first code snippet should not result in an error.

**Output**
For the first code snippet:

```
===============================================================================
                                     CVXPY                                     
                                    v1.1.18                                    
===============================================================================
(CVXPY) Jan 24 01:45:36 PM: Your problem has 1 variables, 0 constraints, and 0 parameters.
(CVXPY) Jan 24 01:45:36 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jan 24 01:45:36 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jan 24 01:45:36 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Jan 24 01:45:36 PM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Jan 24 01:45:36 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> GLPK_MI
(CVXPY) Jan 24 01:45:36 PM: Applying reduction FlipObjective
(CVXPY) Jan 24 01:45:36 PM: Applying reduction Dcp2Cone
(CVXPY) Jan 24 01:45:36 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jan 24 01:45:36 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jan 24 01:45:36 PM: Applying reduction GLPK_MI
(CVXPY) Jan 24 01:45:36 PM: Finished problem compilation (took 4.708e-03 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Jan 24 01:45:36 PM: Invoking solver GLPK_MI  to obtain a solution.
Traceback (most recent call last):
  File "test_mixed_int.py", line 6, in <module>
    print(prob.solve(solver="GLPK_MI", verbose=True))
  File "/Users/benq/Documents/UAT-Optimization/venv/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 473, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/benq/Documents/UAT-Optimization/venv/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 975, in _solve
    solution = solving_chain.solve_via_data(
  File "/Users/benq/Documents/UAT-Optimization/venv/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 343, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/Users/benq/Documents/UAT-Optimization/venv/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py", line 71, in solve_via_data
    results_tup = cvxopt.glpk.ilp(data[s.C],
TypeError: G must be a 'd' matrix
```

**Version**
 - OS: macOS 12.1, Intel chip
 - CVXPY Version: 1.1.18

**Additional context**
 - CVXOPT Version: 1.2.7
 - Related: https://github.com/cvxpy/cvxpy/issues/988

**Comment by allenlawrence94** [comment]
Doesn't mean this isn't a bug, but you can get around this by using integer rather than boolean variables:
```python
import cvxpy as cp

x = cp.Variable(integer=True)
obj = cp.Maximize(0.23 * x)
prob = cp.Problem(obj, constraints=[0 <= x, x <= 1])
print(prob.solve(solver="GLPK_MI", verbose=True))
```

**Comment by SteveDiamond** [comment]
This is a fairly simple fix. All the needed logic is in the CVXOPT interface (https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L152). It should be added to the standard GLPK (non-MIP) interface as well.

**Comment by allenlawrence94** [comment]
I'd be happy to implement! Looks like a simple first contribution

**Comment by allenlawrence94** [comment]
Fix: https://github.com/cvxpy/cvxpy/pull/1621
