### ISSUE TITLE
Compiling with assertions causes issues

### ISSUE THREAD

**Issue by r-barnes** [cvxpy/cvxpy#1690]
**Describe the bug**
Compiling with assertions enabled leads to compile-time and run-time errors!

**To Reproduce**
I modify `setup.py` so that I has the following extension code:
```
canon = Extension(
    '_cvxcore',
    sources=['cvxpy/cvxcore/src/cvxcore.cpp',
             'cvxpy/cvxcore/src/LinOpOperations.cpp',
             'cvxpy/cvxcore/src/Utils.cpp',
             'cvxpy/cvxcore/python/cvxcore_wrap.cxx'],
    include_dirs=['cvxpy/cvxcore/src/',
                  'cvxpy/cvxcore/python/',
                  'cvxpy/cvxcore/include/'],
    extra_compile_args=[
        '-O3',
        '-std=c++11',
        '-Wall',
        '-pedantic',
        not_on_windows('-Wextra'),
        not_on_windows('-Wno-unused-parameter'),
    ],
    extra_link_args=['-O3'],
    undef_macros = [ "NDEBUG" ]  #### ATTENTION!
)
```
setuptools(?) seems to compile code with the `-DNDEBUG` flag on by default. This eliminates all assertions before compilation begins. assertions make us safe, so we should probably include them.

The introduction of the new line `undef_macros = [ "NDEBUG" ]` will cause the C++ code to compiled with assertions included, but this causes issues.

**Expected behavior**
Things compile and run without problems.

**Output**
Compilation issues on current master (TODO):
```
cvxpy/cvxcore/src/LinOpOperations.cpp: In function ‘Tensor get_kronl_mat(const LinOp&, int)’:
cvxpy/cvxcore/src/LinOpOperations.cpp:379:25: error: ‘Eigen::SparseMatrixBase<Eigen::SparseMatrix<double> >::IsRowMajor’ cannot be used as a function
  379 |   assert(!rh.IsRowMajor());
      |                         ^
cvxpy/cvxcore/src/LinOpOperations.cpp: In function ‘Tensor get_vstack_mat(const LinOp&, int)’:
cvxpy/cvxcore/src/LinOpOperations.cpp:430:18: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<const LinOp*>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  430 |   assert(arg_idx <= lin.get_args().size());
      |          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
cvxpy/cvxcore/src/LinOpOperations.cpp: In function ‘Tensor get_hstack_mat(const LinOp&, int)’:
cvxpy/cvxcore/src/LinOpOperations.cpp:470:18: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<const LinOp*>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  470 |   assert(arg_idx <= lin.get_args().size());
      |          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

While running on v1.1.18 (a43aed7) with assertions enabled I get
```
Assertion 'TensorV.count(new_param_id) == 0)' failed.
```
this occurs when I run the homepage example
```
import cvxpy as cp
import numpy

# Problem data.
m = 30
n = 20
numpy.random.seed(1)
A = numpy.random.randn(m, n)
b = numpy.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective is returned by prob.solve().
result = prob.solve()
# The optimal value for x is stored in x.value.
print(x.value)
# The optimal Lagrange multiplier for a constraint
# is stored in constraint.dual_value.
print(constraints[0].dual_value)
```
I haven't been able to reproduce this in my local environment yet, so I think it'd be helpful if his assertion had some info associated with it about what might cause the issue. That is
```
assert(TensorV.count(new_param_id) == 0 && "Explanatory string here...");
```

**Version**
 - OS: Linux
 - CVXPY Version: 1.1.18 for runtime issue; master (b5005d9f209af1) for compile-time issue.

**Additional context**

**Comment by r-barnes** [comment]
@SteveDiamond : I've been able to fix the compilation warnings/issues, but I'm still not sure why I'm getting failures on
```
cvxpy/cvxcore/src/ProblemData.hpp:37: void ProblemData::init_id(int, int): Assertion 'TensorV.count(new_param_id) == 0)' failed.
```
Any info you can provide about what might be going wrong for this to trigger would be helpful!

**Comment by antonio-rojas** [comment]
This is reproducible simply by running the test suite. Backtrace:
```
[Thread debugging using libthread_db enabled]                                                                                                             
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `test-env/bin/python -m pytest -v -k not test_scipy_mi_lp_2'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x000070bf4aea5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x000070bf4ae4c120 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#3  <signal handler called>
#4  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#5  0x000070bf4aea5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#6  0x000070bf4ae4c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#7  0x000070bf4ae334c3 in __GI_abort () at abort.c:79
#8  0x000070bf4ae333df in __assert_fail_base (fmt=0x70bf4afc3c20 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x70bec4314bf8 "TensorV.count(new_param_id) == 0", file=file@entry=0x70bec4314bd0 "cvxpy/cvxcore/src/ProblemData.hpp", 
    line=line@entry=37, function=function@entry=0x70bec4314ba8 "void ProblemData::init_id(int, int)") at assert.c:94
#9  0x000070bf4ae44177 in __assert_fail (assertion=0x70bec4314bf8 "TensorV.count(new_param_id) == 0", 
    file=0x70bec4314bd0 "cvxpy/cvxcore/src/ProblemData.hpp", line=37, function=0x70bec4314ba8 "void ProblemData::init_id(int, int)") at assert.c:103
#10 0x000070bec42fdbef in ProblemData::init_id (this=0x7ffe71d1b5b0, new_param_id=<optimized out>, param_size=<optimized out>)
    at cvxpy/cvxcore/src/ProblemData.hpp:37
#11 init_data_tensor (param_to_size=...) at cvxpy/cvxcore/src/cvxcore.cpp:141
#12 0x000070bec42dd4c0 in build_matrix (num_threads=<optimized out>, constraints=..., var_length=5, id_to_col=std::map with 2 elements = {...}, 
    param_to_size=std::map with 1 element = {...}) at cvxpy/cvxcore/src/cvxcore.cpp:163
#13 _wrap_build_matrix__SWIG_0 (nobjs=5, self=<optimized out>, swig_obj=0x7ffe71d1b650) at cvxpy/cvxcore/python/cvxcore_wrap.cxx:21069
#14 _wrap_build_matrix (self=<optimized out>, args=<optimized out>) at cvxpy/cvxcore/python/cvxcore_wrap.cxx:21168
#15 0x000070bf4b1b1bfc in cfunction_call (func=0x70bec438e4d0, args=0x70bebf25ffb0, kwargs=0x0) at Objects/methodobject.c:548
#16 0x000070bf4b1c4c8a in _PyObject_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bec438e4d0, args=0x70bebf25ffb0, 
    kwargs=<optimized out>) at Objects/call.c:367
#17 0x000070bf4b1905ea in PyCFunction_Call (callable=0x70bec438e4d0, args=0x70bebf25ffb0, kwargs=0x0) at Objects/call.c:387
#18 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:3263
--Type <RET> for more, q to quit, c to continue without paging--c
#19 0x000070bf4b1e3e85 in _PyEval_EvalFrame (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, frame=0x70bf4b80c6a0, throwflag=0)
    at ./Include/internal/pycore_ceval.h:89
#20 _PyEval_Vector (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, func=0x70bebf30ac00, locals=0x0, args=0x70bebe751450, argcount=1, kwnames=<optimized out>)
    at Python/ceval.c:1683
#21 _PyFunction_Vectorcall (func=0x70bebf30ac00, stack=0x70bebe751450, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:419
#22 _PyObject_VectorcallTstate (tstate=<optimized out>, callable=0x70bebf30ac00, args=0x70bebe751450, nargsf=<optimized out>, kwnames=<optimized out>)
    at ./Include/internal/pycore_call.h:92
#23 0x000070bf4b1e3959 in method_vectorcall (method=method@entry=0x70bec56021c0, args=args@entry=0x70bebe751458, nargsf=<optimized out>, 
    kwnames=kwnames@entry=0x70bebe3a3400) at Objects/classobject.c:61
#24 0x000070bf4b1c4cfc in _PyVectorcall_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, func=0x70bf4b1e3700 <method_vectorcall>, 
    callable=0x70bec56021c0, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:283
#25 _PyObject_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bec56021c0, args=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:354
#26 0x000070bf4b1905ea in PyCFunction_Call (callable=0x70bec56021c0, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bebe62f300) at Objects/call.c:387
#27 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:3263
#28 0x000070bf4b1e3e85 in _PyEval_EvalFrame (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, frame=0x70bf4b80c460, throwflag=0)
    at ./Include/internal/pycore_ceval.h:89
#29 _PyEval_Vector (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, func=0x70bf49dba660, locals=0x0, args=0x70bebefebce0, argcount=1, kwnames=<optimized out>)
    at Python/ceval.c:1683
#30 _PyFunction_Vectorcall (func=0x70bf49dba660, stack=0x70bebefebce0, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:419
#31 _PyObject_VectorcallTstate (tstate=<optimized out>, callable=0x70bf49dba660, args=0x70bebefebce0, nargsf=<optimized out>, kwnames=<optimized out>)
    at ./Include/internal/pycore_call.h:92
#32 0x000070bf4b1e3959 in method_vectorcall (method=method@entry=0x70bebecd80c0, args=args@entry=0x70bebefebce8, nargsf=<optimized out>, 
    kwnames=kwnames@entry=0x70bebf114670) at Objects/classobject.c:61
#33 0x000070bf4b1c4cfc in _PyVectorcall_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, func=0x70bf4b1e3700 <method_vectorcall>, 
    callable=0x70bebecd80c0, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:283
#34 _PyObject_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bebecd80c0, args=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:354
#35 0x000070bf4b1905ea in PyCFunction_Call (callable=0x70bebecd80c0, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bebe62e840) at Objects/call.c:387
#36 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:3263
#37 0x000070bf4b1857a1 in _PyObject_FastCallDictTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49dba840, args=0x7ffe71d1c040, 
    nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:144
#38 0x000070bf4b1c20d2 in _PyObject_Call_Prepend (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49dba840, obj=<optimized out>, 
    args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bebe62f740) at Objects/call.c:508
#39 0x000070bf4b298b46 in slot_tp_call (self=0x70bf48c97e30, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwds=0x70bebe62f740) at Objects/typeobject.c:8782
#40 0x000070bf4b18286b in _PyObject_MakeTpCall (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf48c97e30, args=<optimized out>, 
    nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:240
#41 0x000070bf4b18b5b7 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#42 0x000070bf4b1857a1 in _PyObject_FastCallDictTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, args=0x7ffe71d1c3d0, 
    nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:144
#43 0x000070bf4b1c20d2 in _PyObject_Call_Prepend (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, obj=<optimized out>, 
    args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bebe62e900) at Objects/call.c:508
#44 0x000070bf4b298b46 in slot_tp_call (self=0x70bf49c812b0, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwds=0x70bebe62e900) at Objects/typeobject.c:8782
#45 0x000070bf4b1c4c8a in _PyObject_Call (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49c812b0, args=0x70bf4b5cf410 <_PyRuntime+75600>, 
    kwargs=<optimized out>) at Objects/call.c:367
#46 0x000070bf4b1905ea in PyCFunction_Call (callable=0x70bf49c812b0, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bebe62e900) at Objects/call.c:387
#47 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:3263
#48 0x000070bf4b1857a1 in _PyObject_FastCallDictTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, args=0x7ffe71d1c760, 
    nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:144
#49 0x000070bf4b1c20d2 in _PyObject_Call_Prepend (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, obj=<optimized out>, 
    args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bec0322380) at Objects/call.c:508
#50 0x000070bf4b298b46 in slot_tp_call (self=0x70bf49c81440, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwds=0x70bec0322380) at Objects/typeobject.c:8782
#51 0x000070bf4b18286b in _PyObject_MakeTpCall (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49c81440, args=<optimized out>, 
    nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:240
#52 0x000070bf4b18b5b7 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#53 0x000070bf4b1857a1 in _PyObject_FastCallDictTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, args=0x7ffe71d1caf0, 
    nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:144
#54 0x000070bf4b1c20d2 in _PyObject_Call_Prepend (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, obj=<optimized out>, 
    args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bf48bcc4c0) at Objects/call.c:508
#55 0x000070bf4b298b46 in slot_tp_call (self=0x70bf49c81530, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwds=0x70bf48bcc4c0) at Objects/typeobject.c:8782
#56 0x000070bf4b18286b in _PyObject_MakeTpCall (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49c81530, args=<optimized out>, 
    nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:240
#57 0x000070bf4b18b5b7 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#58 0x000070bf4b1857a1 in _PyObject_FastCallDictTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, args=0x7ffe71d1ce80, 
    nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:144
#59 0x000070bf4b1c20d2 in _PyObject_Call_Prepend (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a4dd3a0, obj=<optimized out>, 
    args=0x70bf4b5cf410 <_PyRuntime+75600>, kwargs=0x70bf498fe500) at Objects/call.c:508
#60 0x000070bf4b298b46 in slot_tp_call (self=0x70bf49c80770, args=0x70bf4b5cf410 <_PyRuntime+75600>, kwds=0x70bf498fe500) at Objects/typeobject.c:8782
#61 0x000070bf4b18286b in _PyObject_MakeTpCall (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf49c80770, args=<optimized out>, 
    nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:240
#62 0x000070bf4b18b5b7 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#63 0x000070bf4b24de35 in PyEval_EvalCode (co=0x70bf49c7c4b0, globals=<optimized out>, locals=0x70bf4a7f5fc0) at Python/ceval.c:578
#64 0x000070bf4b26a516 in builtin_exec_impl (module=<optimized out>, source=0x70bf49c7c4b0, globals=0x70bf4a7f5fc0, locals=0x70bf4a7f5fc0, 
    closure=<optimized out>) at Python/bltinmodule.c:1096
#65 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:586
#66 0x000070bf4b1a6a0e in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<optimized out>, args=0x70bf4b80b180, nargsf=<optimized out>, kwnames=0x0)
    at Objects/methodobject.c:438
#67 0x000070bf4b1a68bd in _PyObject_VectorcallTstate (tstate=0x70bf4b62cdb0 <_PyRuntime+458992>, callable=0x70bf4a79c770, args=0x70bf4b80b180, 
    nargsf=9223372036854775810, kwnames=0x0) at ./Include/internal/pycore_call.h:92
#68 PyObject_Vectorcall (callable=0x70bf4a79c770, args=0x70bf4b80b180, nargsf=9223372036854775810, kwnames=0x0) at Objects/call.c:325
#69 0x000070bf4b18b5b7 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#70 0x000070bf4b27f69f in pymain_run_module (modname=<optimized out>, set_argv0=set_argv0@entry=1) at Modules/main.c:300
#71 0x000070bf4b27ef46 in pymain_run_python (exitcode=0x7ffe71d1d554) at Modules/main.c:627
#72 Py_RunMain () at Modules/main.c:713
#73 0x000070bf4b23c5ec in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:767
#74 0x000070bf4ae34e08 in __libc_start_call_main (main=main@entry=0x615ece306120 <main>, argc=argc@entry=6, argv=argv@entry=0x7ffe71d1d7e8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#75 0x000070bf4ae34ecc in __libc_start_main_impl (main=0x615ece306120 <main>, argc=6, argv=0x7ffe71d1d7e8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe71d1d7d8) at ../csu/libc-start.c:360
#76 0x0000615ece306045 in _start ()
```

**Comment by r-barnes** [comment]
@SteveDiamond - just noting that this issue is still open and causing problems.

**Comment by Transurgeon** [comment]
@r-barnes I am looking into this to try and fix the conda builds for OSX. Any suggestions on how to replicate and/or fix the issue?
