### ISSUE TITLE
Solving a fractional linear boolean problem

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1709]
This issue contains two potential bugs which I think need investigation:

1. Does the grammatically obscure error message `Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dbe0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)` coming from SCIP mean that the cvxpy SCIP interface is faulty?
2.  Are the non-boolean results from CBC due to an interface bug, or a bug in CBC itself?

_________________________________________________________________

I'm solving fractional linear boolean quasiconvex problems with a simple bisection method (it's not DQP, so I can't use the dqp=True option).    I would like to report my experiences with the following code (output below):
 - GLPK_MI works perfectly
 - SCIP works in a sense, but is pretty much unusable because of the repeated error messages
 - CBC returns solutions which violate the boolean constraints - looks like a CBC bug to me
 - ECOS_BB crashes badly - I think this is a known problem.

So the overall score is only about 1/4.

```

from sys import exit
from time import time
from itertools import product
import numpy as np
import cvxpy as cp

class Fractional_QUBO:
  '''
   max_x (x.T@A@x)/(x.T@B@x) for A,B both symmetric positive definite
  '''
  def __init__(s,A,B,pp_con=False):
    s.n=A.shape[0]
    assert s.n==A.shape[1]
    assert s.n==B.shape[0]
    assert s.n==B.shape[1]
    assert np.all(A.T==A) # insist that A and B are symmetric
    assert np.all(B.T==B)
    s.A=A
    s.B=B
    s.x=cp.Variable(s.n,name=f'x',boolean=True)
    s.nvars=s.n
    s.xij={}
    s.con=[]
    num=[]
    den=[]
    for i in range(s.n):
      # diagonal terms...
      if A[i,i]!=0.0: num.append(A[i,i]*s.x[i])
      if B[i,i]!=0.0: den.append(B[i,i]*s.x[i])
      for j in range(s.n):
        if i==j: continue
        # off-diagonal terms...
        if A[i,j]!=0.0:
          if (i,j) not in s.xij:
            name=f'x[{s.nvars}]'
            s.xij[i,j]=cp.Variable(name=name,boolean=True)
            s.nvars+=1
          num.append(1*A[i,j]*s.xij[i,j])
          s.con.append(s.xij[i,j]-s.x[i]<=0)
          s.con.append(s.xij[i,j]-s.x[j]<=0)
          s.con.append(s.x[i]+s.x[j]-s.xij[i,j]<=1)
        if B[i,j]!=0.0:
          if (i,j) not in s.xij:
            s.xij[i,j]=cp.Variable(name=f'x[{s.nvars}]',boolean=True)
            s.nvars+=1
          den.append(1*B[i,j]*s.xij[i,j])
          s.con.append(s.xij[i,j]-s.x[i]<=0)
          s.con.append(s.xij[i,j]-s.x[j]<=0)
          s.con.append(s.x[i]+s.x[j]-s.xij[i,j]<=1)
      s.num,s.den=cp.sum(num),cp.sum(den)
      s.obj=s.num/s.den

  def solve(s,solver='GLPK_MI'):
    # solvers: 'ECOS_BB','GLPK_MI','CBC','SCIP'
    problem=cp.Problem(cp.Maximize(s.obj),s.con)
    if not problem.is_dqcp():
      print('solve: problem is not DQP')
      return
    print(f'solver={solver}:')
    problem.solve(qcp=True,solver=solver)
    print(f'  status={problem.status}')
    if problem.status==cp.OPTIMAL:
      print(f'  Optimal value={problem.value:.4f}')
      print(f'  x={s.x.value}')

  def exhaustive_search(s):
    n=s.A.shape[0]
    gmax=-1e300
    for y in product((0,1),repeat=n):
      x=np.array(y)
      if np.all(x==0): continue
      xH=np.conj(x.T)
      den=np.real(xH@s.B@x)
      assert den>0.0
      g=np.real(xH@s.A@x)/den
      if g>gmax:
        gmax=g
        w=x.copy()
    return gmax,np.array(w,dtype=int)

  def bisect(s,dbg=False,solver='GLPK_MI'):
    print(f'solver={solver}')
    best=-1.0
    for i in range(s.n): # fix x[i]==1
      if dbg: print(f'constraining x[{i}]==1...')
      dn,up=0.0,1e2
      abort=False
      while abs(up-dn)>1e-4:
        t=0.5*(dn+up)
        problem=cp.Problem(cp.Minimize(0),[s.x[i]==1,s.num>=t*s.den]+s.con)
        problem.solve(solver=solver)
        if problem.status==cp.OPTIMAL:
          b=np.round(s.x.value)
          if not np.allclose(b,s.x.value):
            print(f'\nx={s.x.value} is not boolean, aborting!')
            abort=True
            break
          if dbg: print(f'<{t:.3f}',end=' ')
          #  {list(q.value for q in s.xij.values())}
          dn=t
          if t>best: best,x=t,s.x.value
        elif problem.status==cp.INFEASIBLE:
          if dbg: print(f'>{t:.3f}',end=' ')
          if t<best: # can abort as we already have a better choice for i
            print(f'\naborting for x[{i}]==1 as we already have a better choice')
            abort=True
            break
          up=t
        else:
          print(problem.status)
          raise Exception('CVXPY error in bisect!')
      if dbg and not abort: print(f'\nconverged to {t:.3f}')
    x=np.array(x,dtype=int)
    return best,x

if __name__=='__main__':
  np.set_printoptions(precision=2,linewidth=200)
  print(f'numpy version={np.__version__}')
  print(f'cvxpy version={cp.__version__}')
  rng=np.random.default_rng(1)
  # solvers: 'ECOS_BB','GLPK_MI','CBC','SCIP'
  # 'SCIP' and 'GLPK_MI' work... ['ECOS_BB' crashes]
  for n in (10,):
    print(f'n={n}')
    A=rng.integers(low=-5,high=5,size=(n,n))
    B=rng.integers(low=-5,high=5,size=(n,n))
    A=A@A.T # make A symmetric positive definite
    B=B@B.T # make B symmetric positive definite
    assert np.all(np.linalg.eig(A)[0]>0)
    assert np.all(np.linalg.eig(B)[0]>0)
    fq=Fractional_QUBO(A,B)
    t0=time()
    exh=fq.exhaustive_search()
    print(f'exhaustive_search: {exh[0]:.4f} at {exh[1]} in {time()-t0:.2f}s.')
    for solver in ('GLPK_MI','SCIP','CBC','ECOS_BB'):
      t0=time()
      best,x=fq.bisect(dbg=True,solver=solver)
      print(f'bisect:            {best:.4f} at {x} in {time()-t0:.2f}s.')
      print(f'exhaustive_search: {exh[0]:.4f} at {exh[1]} in {time()-t0:.2f}s.')
```

```numpy version=1.22.3
cvxpy version=1.3.0.dev0+Unknown.Unknown
n=10
exhaustive_search: 3.7091 at [0 0 0 0 0 1 0 0 1 0] in 0.01s.
solver=GLPK_MI
constraining x[0]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 <3.416 >3.417 >3.417 <3.417 >3.417 
converged to 3.417
constraining x[1]==1...
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[1]==1 as we already have a better choice
constraining x[2]==1...
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[2]==1 as we already have a better choice
constraining x[3]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 <3.416 >3.417 >3.417 <3.417 >3.417 
converged to 3.417
constraining x[4]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 >3.416 
aborting for x[4]==1 as we already have a better choice
constraining x[5]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 <3.516 >3.711 <3.613 <3.662 <3.687 <3.699 <3.705 <3.708 >3.709 <3.709 <3.709 >3.709 <3.709 
converged to 3.709
constraining x[6]==1...
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[6]==1 as we already have a better choice
constraining x[7]==1...
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[7]==1 as we already have a better choice
constraining x[8]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 <3.516 >3.711 <3.613 <3.662 <3.687 <3.699 <3.705 <3.708 >3.709 <3.709 <3.709 >3.709 <3.709 
converged to 3.709
constraining x[9]==1...
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[9]==1 as we already have a better choice
bisect:            3.7091 at [0 0 0 0 0 1 0 0 1 0] in 37.53s.
exhaustive_search: 3.7091 at [0 0 0 0 0 1 0 0 1 0] in 37.53s.

solver=SCIP
constraining x[0]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8da60>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d040>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d280>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d760>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8db80>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db3c6a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db3c700>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db3ca60>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db3c1c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e6377c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e637b80>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 <3.416 >3.417 >3.417 <3.417 >3.417 
converged to 3.417
constraining x[1]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dca0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dee0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8da00>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dbe0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dc40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[1]==1 as we already have a better choice
constraining x[2]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d7c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d5e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dca0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dee0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8da00>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[2]==1 as we already have a better choice
constraining x[3]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dbe0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dc40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d7c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d5e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8dee0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e6375e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e6376a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8df40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114040>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1894c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189160>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 <3.416 >3.417 >3.417 <3.417 >3.417 
converged to 3.417
constraining x[4]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e637700>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e6375e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e6376a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e637e80>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189880>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114340>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114ca0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1147c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114820>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 >3.516 <3.320 >3.418 <3.369 <3.394 <3.406 <3.412 <3.415 >3.416 
aborting for x[4]==1 as we already have a better choice
constraining x[5]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189fa0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1893a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189d00>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1891c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189220>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114a60>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db8d8e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114520>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114dc0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189be0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 <3.516 >3.711 <3.613 <3.662 <3.687 <3.699 <3.705 <3.708 >3.709 <3.709 <3.709 >3.709 >3.709 
converged to 3.709
constraining x[6]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189280>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189c40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189ee0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189460>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189340>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[6]==1 as we already have a better choice
constraining x[7]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189520>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1890a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189220>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189160>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189dc0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[7]==1 as we already have a better choice
constraining x[8]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1898e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189100>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189fa0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189c40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1893a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114a00>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772db3cb20>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e114220>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1897c0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1899a0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 <3.125 >4.688 >3.906 <3.516 >3.711 <3.613 <3.662 <3.687 <3.699 <3.705 <3.708 >3.709 <3.709 <3.709 >3.709 >3.709 
converged to 3.709
constraining x[9]==1...
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189460>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e1892e0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189a60>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189c40>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
Error encountered when optimising <pyscipopt.scip.Model object at 0x7f772e189dc0>: getSolObjVal cannot only be called in stage SOLVING without a valid solution (current stage: 10)
>50.000 >25.000 >12.500 >6.250 >3.125 
aborting for x[9]==1 as we already have a better choice
bisect:            3.7090 at [0 0 0 0 0 1 0 0 1 0] in 46.12s.
exhaustive_search: 3.7091 at [0 0 0 0 0 1 0 0 1 0] in 46.12s.

solver=CBC
constraining x[0]==1...

x=[1.   0.   0.   0.48 0.48 0.48 0.   0.48 0.48 0.48] is not boolean, aborting!
constraining x[1]==1...
>50.000 >25.000 >12.500 
x=[0.5  1.   0.45 0.5  0.5  0.5  0.45 0.5  0.5  0.5 ] is not boolean, aborting!
constraining x[2]==1...

x=[0.5  0.5  1.   0.5  0.5  0.5  0.5  0.5  0.5  0.42] is not boolean, aborting!
constraining x[3]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 
x=[0.5 0.  0.  1.  0.5 0.5 0.  0.5 0.5 0. ] is not boolean, aborting!
constraining x[4]==1...
>50.000 >25.000 >12.500 
x=[0.5 0.  0.  0.5 1.  0.5 0.  0.5 0.5 0. ] is not boolean, aborting!
constraining x[5]==1...
>50.000 >25.000 >12.500 >6.250 <3.125 
x=[0.5  0.   0.   0.5  0.38 1.   0.   0.5  0.5  0.  ] is not boolean, aborting!
constraining x[6]==1...
>50.000 
x=[0.5  0.5  0.31 0.5  0.5  0.5  1.   0.5  0.5  0.5 ] is not boolean, aborting!
constraining x[7]==1...

x=[0.5 0.5 0.  0.5 0.5 0.5 0.  1.  0.5 0.5] is not boolean, aborting!
constraining x[8]==1...
>50.000 
x=[0.5  0.09 0.   0.5  0.5  0.5  0.   0.5  1.   0.5 ] is not boolean, aborting!
constraining x[9]==1...

x=[0.38 0.   0.   0.38 0.38 0.38 0.   0.38 0.38 1.  ] is not boolean, aborting!
bisect:            3.1250 at [1 0 0 1 0 1 0 0 1 0] in 9.24s.
exhaustive_search: 3.7091 at [0 0 0 0 0 1 0 0 1 0] in 9.24s.

solver=ECOS_BB
constraining x[0]==1...
/usr/local/lib/python3.8/dist-packages/cvxpy-1.3.0-py3.8-linux-x86_64.egg/cvxpy/problems/problem.py:1333: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(
>50.000 infeasible_inaccurate
Traceback (most recent call last):
  File "fractional_QUBO_02.py", line 143, in <module>
    best,x=fq.bisect(dbg=True,solver=solver)
  File "fractional_QUBO_02.py", line 114, in bisect
    raise Exception('CVXPY error in bisect!')
Exception: CVXPY error in bisect!
```

**Comment by SteveDiamond** [comment]
I installed cvxpy from source and Cbc via ``pip install cylp``. The code above worked fine for me. This is on mac with Python 3.10.

**Comment by SteveDiamond** [comment]
All related issues are addressed in the latest patch (deployed to pypi).
