### ISSUE TITLE
Using SCS-solver generates "ValueError: Error parsing inputs"

### ISSUE THREAD

**Issue by muhlbach** [cvxpy/cvxpy#1717]
**THANK YOU**
Before describing the bug, let me once again start out by thanking all maintainers at CVXPY for their awesome job!!!

**Describe the bug**
When wrapping CVXPY into a class, the SCS solver does not work (in the following example), but other solvers (e.g., CVXOPT) work just fine.

Using SCS, it throws the following error:

```
Traceback (most recent call last):

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_11925/276870502.py", line 1, in <cell line: 1>
    results = finetuner.finetune_concept_embeddings(Y=Y,

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_11925/2591882114.py", line 247, in finetune_concept_embeddings
    R_optim, beta_optim = self._finetune_concept_embeddings(Y=Y,

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_11925/2591882114.py", line 219, in _finetune_concept_embeddings
    R_optim, beta_optim = self._finetune_multiple_concept_embeddings(Y=Y,

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_11925/2591882114.py", line 203, in _finetune_multiple_concept_embeddings
    self._solve(Y=Y,

  File "/var/folders/lg/d49pbfkx1mxg1y8v5l810v4w0000gn/T/ipykernel_11925/2591882114.py", line 122, in _solve
    problem.solve(verbose=self.verbose, solver=self.solver, ignore_dpp=True, max_iters=self.max_iters)

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1012, in _solve
    solution = solving_chain.solve_via_data(

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 361, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 329, in solve_via_data
    results, status = solve(solver_opts)

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 324, in solve
    _results = scs.solve(args, cones, verbose=verbose, **_solver_opts)

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/scs/__init__.py", line 166, in solve
    solver = SCS(data, cone, **settings)

  File "/Users/muhlbach/opt/anaconda3/envs/develop/lib/python3.8/site-packages/scs/__init__.py", line 118, in __init__
    self._solver = _scs.SCS(

ValueError: Error parsing inputs
```

**To Reproduce**
Using this, one should be able to reproduce the error. Please ignore that the class seems overly complicated as of now. I've stripped away lots of functionalities to make it as minimal as possible. Again, using CVXOPT it works fine.

```
import numpy as np
import cvxpy as cp
import scipy as sp

class FineTuner(object):
    def __init__(self,
                  loss_fnc="fro",
                  max_iters=10000,
                  solver=cp.CVXOPT,
                  verbose=False):        
        self.loss_fnc = loss_fnc
        self.max_iters = max_iters
        self.solver=solver
        self.verbose = verbose
        
    def _prepare_R(self,
                   estimate=False,
                   nonneg=False,
                   nonpos=False,
                   symmetric=False,
                   diag=True,
                   PSD=False,
                   NSD=False,
                   boolean=False,
                   integer=False,
                   pos=False,
                   neg=False):
        
        if estimate:
            R = cp.Variable(shape=(self.d,self.d),
                            nonneg=nonneg,
                            nonpos=nonpos,
                            symmetric=symmetric,
                            diag=diag,
                            PSD=PSD,
                            NSD=NSD,
                            boolean=boolean,
                            integer=integer,
                            pos=pos,
                            neg=neg)
        else:
            R = np.identity(n=self.d)
            
        return R
                
    
    def _general_loss(self,x,loss_fnc):
        """ Generate general loss without regularization """
        
        if loss_fnc in ["nuc", "fro", "inf"]:
            loss = cp.norm(x=x, p=loss_fnc)
            
        elif loss_fnc=="spectral":
            loss = cp.norm(x=x, p=2)
            
        return loss
        
    def _reg_loss(self,x,loss_fnc,penalty):
        """ Generate regularization loss  """
        
        loss = cp.multiply(penalty, self._general_loss(x=x,loss_fnc=loss_fnc))
    
        return loss

    def _prepare_loss(self,Y,E,R,A,beta,loss_fnc,penalty_R=0,penalty_beta=0):
        """ Generate loss = main_loss + regularization_loss """
        
        loss_input = Y - E @ R @ A.T @ beta
        
        loss = self._general_loss(x=loss_input,loss_fnc=self.loss_fnc)
        
        if penalty_R != 0:
            loss += self._reg_loss(x=R,loss_fnc=self.loss_fnc,penalty=penalty_R)
        
        if penalty_beta != 0:
            loss += self._reg_loss(x=beta,loss_fnc=self.loss_fnc,penalty=penalty_beta)

        return loss
            
    def _extract_value(self, x):
        if isinstance(x, cp.expressions.variable.Variable):
            x = x.value

        if sp.sparse.issparse(x):
            x = x.toarray()
            
        return x
        
    def _solve(self, Y, E, A, R, beta, loss_fnc, penalty_R, penalty_beta):

        # Reset penalty if argument is in fact not a Variable
        if not isinstance(R, cp.expressions.variable.Variable):
            penalty_R = 0
        
        if not isinstance(beta, cp.expressions.variable.Variable):
            penalty_beta = 0
        
        # Construct loss
        loss = self._prepare_loss(Y=Y,
                                  E=E,
                                  R=R,
                                  A=A,
                                  beta=beta,
                                  loss_fnc=loss_fnc,
                                  penalty_R=penalty_R,
                                  penalty_beta=penalty_beta)
        
        # Set up constraints        
        constraints = []
        
        # Set up objective function
        Q = cp.Minimize(loss)

        # Set up problem
        problem = cp.Problem(objective=Q, constraints=constraints)

        problem.solve(verbose=self.verbose, solver=self.solver, ignore_dpp=True, max_iters=self.max_iters)
    
        
    def _finetune_multiple_concept_embeddings(self,
                                              # Data
                                              Y,
                                              E,
                                              A,
                                              
                                              # Meta parameters
                                              estimate_R=False,
                                              penalty_R=0,
                                              penalty_beta=0,
                                              
                                              # R parameters
                                              R_nonneg=False,
                                              R_nonpos=False,
                                              R_symmetric=False,
                                              R_diag=False,
                                              R_PSD=False,
                                              R_NSD=False,
                                              R_boolean=False,
                                              R_integer=False,
                                              R_pos=False,
                                              R_neg=False,
                                              
                                              # Beta parameters
                                              beta_nonneg=False,
                                              beta_nonpos=False,
                                              beta_symmetric=False,
                                              beta_diag=False,
                                              beta_PSD=False,
                                              beta_NSD=False,
                                              beta_boolean=False,
                                              beta_integer=False,
                                              beta_pos=False,
                                              beta_neg=False
                                              ):
        """
        Consider the problem of:
            {R,beta} = argmin ||Y - E * R * A' * beta||,
            where:
                Y is (Nx1)-dim vector of outcomes that are jointly captured by concept embeddings in A
                E is (Nxd)-dim matrix of occupational embeddings
                A is (Mxd)-dim matrix of multiple concept embeddings
                
                beta is (Mx1)-dim vector of weights on the multiple concept embeddings
                R is (dxd)-dim rotation matrix
                
                N is the number of occupations
                M is the number of concepts
                d is the embedding dimension
        """
        if not estimate_R:
            # Zero loss if we do not estimate R
            penalty_R=0
            
        R = self._prepare_R(estimate=estimate_R,
                            nonneg=R_nonneg,
                            nonpos=R_nonpos,
                            symmetric=R_symmetric,
                            diag=R_diag,
                            PSD=R_PSD,
                            NSD=R_NSD,
                            boolean=R_boolean,
                            integer=R_integer,
                            pos=R_pos,
                            neg=R_neg)
        
        beta = cp.Variable(shape=(self.M,1),
                            nonneg=beta_nonneg,
                            nonpos=beta_nonpos,
                            symmetric=beta_symmetric,
                            diag=beta_diag,
                            PSD=beta_PSD,
                            NSD=beta_NSD,
                            boolean=beta_boolean,
                            integer=beta_integer,
                            pos=beta_pos,
                            neg=beta_neg)
                
        self._solve(Y=Y,
                    E=E,
                    R=R,
                    A=A,
                    beta=beta,
                    loss_fnc=self.loss_fnc,
                    penalty_R=penalty_R,
                    penalty_beta=penalty_beta)


        return R, beta    



    def _finetune_concept_embeddings(self,Y,E,A,**kwargs):
        
        R_optim, beta_optim = self._finetune_multiple_concept_embeddings(Y=Y,
                                                                         E=E,
                                                                         A=A,
                                                                         **kwargs)

        # Extract solution
        R_optim = self._extract_value(x=R_optim)
        beta_optim = self._extract_value(x=beta_optim)
             
        return R_optim, beta_optim

    # -------------------------------------------------------------------------
    # Public functions
    # -------------------------------------------------------------------------
    def finetune_concept_embeddings(self,Y,E,A):

        # ---------------------------------------------------------------------
        # Prep
        # ---------------------------------------------------------------------
        # Get dimensions
        self.N = Y.shape[0] # Number of occupations
        self.r = Y.shape[1] # Number of indicators of concept
        self.d = E.shape[1] # Number of embedding dimensions
        self.M = A.shape[0] # Number of concepts
                        
        # ---------------------------------------------------------------------
        # Main
        # ---------------------------------------------------------------------        
        R_optim, beta_optim = self._finetune_concept_embeddings(Y=Y,
                                                                E=E,
                                                                A=A)

        # Compute loss on test data
        loss_input = Y - E @ R_optim @ A.T @ beta_optim

        loss = np.linalg.norm(x=loss_input, ord="fro")
   
        results = {"loss" : loss,
                   "R" : R_optim,
                   "beta" : beta_optim
                   }

            
        return results


#################### BEGIN HERE ####################
# Settings        
N = 100
d = 10
M = 2
r = 1

# Generate random data
Y = np.random.normal(size=(N,r))
E = np.random.normal(size=(N,d))
A = np.random.normal(size=(M,d))

# Instantiate
finetuner = FineTuner(verbose=2,
                      solver=cp.SCS)

# Solve
results = finetuner.finetune_concept_embeddings(Y=Y,
                                                E=E,
                                                A=A)
``

**Expected behavior**
I believe it should be able to run this way.

**Version**
 - OS: macOS 12.2.1
 - CVXPY Version:  v1.2.0

**Comment by SteveDiamond** [comment]
What version of SCS do you have?

**Comment by muhlbach** [comment]
SCS v3.2.0 (I should have mentioned that, my apologies).

The weird thing is that if I solve the problem directly (not wrapped in the class), it works fine. It is exactly the same procedure as in the class, where all data arguments just get passed through methods. Otherwise the CVXOPT wouldn't work.

```
import numpy as np
import cvxpy as cp

# Settings        
N = 100
d = 10
M = 2
r = 1

# Generate random data
Y = np.random.normal(size=(N,r))
E = np.random.normal(size=(N,d))
A = np.random.normal(size=(M,d))

R = np.identity(n=d)

beta = cp.Variable(shape=(M,1))    
    
loss_input = Y - E @ R @ A.T @ beta

loss = cp.norm(x=loss_input, p="fro")

# Set up constraints        
constraints = []

# Set up objective function
Q = cp.Minimize(loss)

# Set up problem
problem = cp.Problem(objective=Q, constraints=constraints)

problem.solve(verbose=True, solver=cp.SCS, ignore_dpp=True, max_iters=100)
```

**Comment by rileyjmurray** [comment]
@muhlbach when I run it with SCS 3.1 I get the following error
```
  File "/home/riley/anaconda3/envs/cvx39/lib/python3.9/site-packages/scs/__init__.py", line 110, in solve
    return _scs_direct.csolve((m, n), Adata, Aindices, Acolptr, Pdata, Pindices,
TypeError: argument 12 must be bool, not int
```
So I changed 
```
    # Instantiate
    finetuner = FineTuner(verbose=2,
                          solver=cp.SCS)
```
to
```
    finetuner = FineTuner(verbose=True, solver=cp.SCS)
```
and everything worked fine. So you should change your call to ``prob.solve`` to something like
```
        if self.solver == 'SCS':
            verbose = bool(self.verbose)
        else:
            verbose = self.verbose
        problem.solve(verbose=verbose, solver=self.solver, ignore_dpp=True, max_iters=self.max_iters)
```
I've verified that works on my machine when when calling ``finetuner = FineTuner(verbose=2, solver=cp.SCS)``.

I believe that should resolve your issue with SCS 3.2 as well. Please go ahead and close this issue if it does.

Thanks!

**Comment by muhlbach** [comment]
Ah, the error message from version 3.1 is easier to debug. I should've considered checking another version. This works like a charm. Thank you a lot guys, @SteveDiamond, @rileyjmurray, highly appreciated!
