### ISSUE TITLE
cp.sum is inconsistent with np.ndarray

### ISSUE THREAD

**Issue by michael-123123** [cvxpy/cvxpy#1784]
**Describe the bug**
`cp.sum` does not apply consistently when the input is a numpy array.
Specifically, if the array is composed of constant values, `cp.sum` works fine. 
Otherwise, it crashes.

I realize that I can wrap the numpy array with an `hstack` or a `vstack` but doing so entails heavy performance penalties (upto x3 time).

**To Reproduce**
`cp.sum(npasarray([1,2,3,cp.Variable(),4,5]))`

**Expected behavior**
I think that either `cp.sum` should not accept numpy arrays or it should forward calls to `np.ndarray.sum` which also accepts `axis` and `keepdims` parameters.

**Output**
```
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy as cp
>>> import numpy as np
>>> cp.sum(np.asarray([1,2,3,cp.Variable(),4,5]))
TypeError: float() argument must be a string or a number, not 'Variable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/atoms/affine/sum.py", line 114, in sum
    return Sum(expr, axis, keepdims)
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/atoms/affine/sum.py", line 43, in __init__
    super(Sum, self).__init__(expr, axis=axis, keepdims=keepdims)
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/atoms/axis_atom.py", line 36, in __init__
    super(AxisAtom, self).__init__(expr)
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 49, in __init__
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/atoms/atom.py", line 49, in <listcomp>
    self.args = [Atom.cast_to_const(arg) for arg in args]
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 472, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/expressions/constants/constant.py", line 48, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "/home/michael/opt/miniconda3/envs/roomassignments/lib/python3.7/site-packages/cvxpy/interface/numpy_interface/ndarray_interface.py", line 53, in const_to_matrix
    return result.astype(numpy.float64)
ValueError: setting an array element with a sequence.
```
**Version**
 - OS: Ubuntu 20.04.3
 - CVXPY Version: 1.1.17

**Additional context**

Possible untested fix (in `atoms/affine/sum.py`):

```
@wraps(Sum)
def sum(expr, axis: Optional[int] = None, keepdims: bool = False):
    """Wrapper for Sum class.
    """
    if isinstance(expr, list):
        return __builtins__['sum'](expr)
    elif isinstance(expr, np.ndarray):
        return expr.sum(axis=axis, keepdims=keepdims)
    else:
        return Sum(expr, axis, keepdims)

```

**Comment by SteveDiamond** [comment]
I don't think it's so simple as the fix you propose. You have an object array, and it's going to remain an object array unless it's 100% reduced (i.e. down to a scalar). cvxpy is not at all set up to have object arrays floating around internally. In general we strongly discourage applying numpy functions to cvxpy objects. I'll flag @phschiele who is working with Michael Sommerauer on speeding up canonicalization. hstack and vstack can be made much lower overhead I believe. But in terms of this specific issue it would be better for sum to raise an error.

**Comment by SteveDiamond** [comment]
Related, we need to add support for sparse variables, which could help here via ``cp.sum(constant + sparse variable)`` instead of using hstack/vstack.

**Comment by michael-123123** [comment]
Ok. Thanks.

**Comment by phschiele** [comment]
@michael-123123 Can you explain the testing you did to come up with the "up to x3 time" performance penalty for stacking? I'd like to see what the bottleneck is here.

**Comment by michael-123123** [comment]
Hi @phschiele -- sure.
The biggest issue is with hstack - because it does a lot of reshaping.

an example test program:


```
from timeit import default_timer

import numpy as np
import cvxpy as cp


def with_builtin(array):
    return sum(array)


def with_sum(array):
    return np.sum(array)


def with_hstack(array):
    return cp.sum(cp.hstack(array))


def run():
    def measure(callback, *args, ntimes=1000, **kwargs):
        start = default_timer()
        for _ in range(ntimes):
            callback(*args, **kwargs)
        return default_timer() - start

    array = list(range(30)) + [cp.Variable() for _ in range(10)] + list(range(10))
    array = np.asarray(array)

    builtin_time = measure(with_builtin, array)
    sum_time = measure(with_sum, array)
    hstack_time = measure(with_hstack, array)

    print("sum   :", builtin_time)
    print("np.sum:", sum_time)
    print("hstack:", hstack_time)


run()


"""
sum   : 0.6311480979202315
np.sum: 0.5977825070731342
hstack: 1.8946616819594055
"""

```

**Comment by phschiele** [comment]
Thanks for the nice snippet, @michael-123123 !
I did some digging and it turns out that `hstack` is slower because of the way the size is computed.
This is quite surprising, but by replacing the `np.prod(shape)` in `expression.py` and `reshape.py` with the function below, I see much better performance (before it was similar to your results).
```
sum   : 0.4969825009975466
np.sum: 0.49813795799855143
hstack: 0.6365642130040214
```

```py
def size_from_shape(shape) -> int:
    if shape:
        return reduce(mul, shape)
    else:
        return 1
```

The slowdown in `np.prod` occurs in `__array_function__`, see below. Other people seem to have observed similar issues, e.g. [here](https://github.com/numpy/numpy/issues/14776).

![image](https://user-images.githubusercontent.com/44360364/171794372-58ead59f-b7a9-4876-a61a-6a3bd7275074.png)

**Comment by michael-123123** [comment]
hi @phschiele 

Thanks for the explanation.
In that case - would `size_from_shape` be changed to use `reduce` in future versions of CVXPY?

**Comment by phschiele** [comment]
I don't see a big downside to changing it. If the maintainers agree, a PR would be most welcome. Perhaps `utilities/shape.py` would be a good place to house this function.

**Comment by michael-123123** [comment]
ok - thanks

**Comment by rileyjmurray** [comment]
Hi @michael-123123. I agree with @phschiele, this is the kind of change that could go in a minor release (the eventual 1.3.0).

CC: @SteveDiamond @akshayka. What do you two think?

**Comment by SteveDiamond** [comment]
Definitely, it's a very welcome improvement!

**Comment by adishavit** [comment]
@phschiele what software did you use to make this graph?
 
> ![image](https://user-images.githubusercontent.com/44360364/171794372-58ead59f-b7a9-4876-a61a-6a3bd7275074.png)

**Comment by phschiele** [comment]
> @phschiele what software did you use to make this graph? Very cool!
> 
> 
> 
>  
> 
> > ![image](https://user-images.githubusercontent.com/44360364/171794372-58ead59f-b7a9-4876-a61a-6a3bd7275074.png)
> 
> 

@adishavit it's called [snakeviz](https://jiffyclub.github.io/snakeviz/)

**Comment by rileyjmurray** [comment]
@michael-123123 @phschiele It seems like we should close this issue. Before doing that I want to clearly record what we changed and what we did not change. It seems that a speed issue was fixed. Was the underlying "inconsistency" with NumPy also fixed? If not, then we should change the title of this GitHub Issue before closing.

**Comment by michael-123123** [comment]
Hi @rileyjmurray 

The PR I submitted only made a change in `Expression` and in `reshape`, replacing a call to numpy with a call to `size_from_shape`.

As far as I understand, there are additional places where this might be done. However, these are not included in this PR.

**Comment by rileyjmurray** [comment]
I’m just trying to see if the name of the issue is appropriate. If people
search for something similar in the future and find a closed issue than
that issue should be relevant.

**Comment by michael-123123** [comment]
@rileyjmurray I think you're right.
there are actually two issues here: incompatibility of cp.sum and np.ndarray and performance issue.
we can incorporate both into the title.
if anyone has a suggestion - lmk and I'll change the title.
