### ISSUE TITLE
Error resulting from constraint on an inverse product 

### ISSUE THREAD

**Issue by aengl5337** [cvxpy/cvxpy#1873]
**Describe the bug**
I am writing a script to output RLC values given a desired skeleton operational amplifier circuit in an attempt to select components that will minimize noise over a given frequency band.

**Expected behavior**  
Ultimately, I want to put a lower bound on the overall gain of the circuit by crafting each opamp gain to be a convex/concave function, and then constraining the inverse product of these gains from above.

**To Reproduce**
The error comes from the following lines, where I define the inverse product of the sequence of gains obtained from each stage of the circuit (Ginv).  Upon removing the constraint, the code executes successfully.

The scripts are somewhat lengthy -- I can include more detail if needed. 

Note that the arguments of inv_prod are concave or affine (see the below for the type output of each entry) such that Ginv is convex.
Gp = 
[0.15,
 Expression(AFFINE, NONPOSITIVE, ()),
 Expression(CONVEX, NONNEGATIVE, ()),
 Expression(CONVEX, NONNEGATIVE, ()),
 Expression(CONCAVE, NONPOSITIVE, ())]

**CODE**
`Ginv = cp.inv_prod(cp.hstack([Gp[0],Gp[1],-Gp[2],-Gp[3],Gp[4]])) # NOTE: dual output auto-constrained to have same gain

obj = cp.Minimize(cp.sum(e_out_p))
constr = []
constr += [Ginv <= 2]

p = cp.Problem(obj,constr)
p.solve(verbose = True)
print(obj.value)
print(X.value)`

**Output**

-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Aug 15 06:34:17 PM: Compiling problem (target solver=ECOS).
(CVXPY) Aug 15 06:34:17 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Aug 15 06:34:17 PM: Applying reduction Dcp2Cone
Traceback (most recent call last):

  File "C:\Users\Alec\Documents\Export to Drive\SPI\QPD\python\optVals.py", line 83, in <module>
    p.solve(verbose = True)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\problems\problem.py", line 473, in solve
    return solve_func(self, *args, **kwargs)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\problems\problem.py", line 967, in _solve
    solver, gp, enforce_dpp, verbose)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\problems\problem.py", line 627, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\chain.py", line 76, in apply
    problem, inv = r.apply(problem)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\dcp2cone\dcp2cone.py", line 43, in apply
    return super(Dcp2Cone, self).apply(problem)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\canonicalization.py", line 68, in apply
    constraint)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\canonicalization.py", line 99, in canonicalize_tree
    canon_arg, c = self.canonicalize_tree(arg)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\canonicalization.py", line 102, in canonicalize_tree
    canon_expr, c = self.canonicalize_expr(expr, canon_args)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\canonicalization.py", line 113, in canonicalize_expr
    return self.canon_methods[type(expr)](expr, args)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\reductions\dcp2cone\atom_canonicalizers\power_canon.py", line 43, in power_canon
    return t, gm_constrs(x, [t, ones], w)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\utilities\power_tools.py", line 65, in gm_constrs
    tree = decompose(w)

  File "C:\Users\Alec\anaconda3\envs\tf\lib\site-packages\cvxpy\utilities\power_tools.py", line 597, in decompose
    if t not in tree:

  File "C:\Users\Alec\anaconda3\envs\tf\lib\fractions.py", line 559, in __hash__
    dinv = pow(self._denominator, _PyHASH_MODULUS - 2, _PyHASH_MODULUS)

TypeError: unsupported operand type(s) for pow(): 'numpy.int32', 'int', 'int'

**Version**
 - OS: Windows 11
 - CVXPY Version: 1.1.18
 - Python Version: 3.7.7

Thank you!

**Comment by SteveDiamond** [comment]
I think this is a dumb windows bug. Here is the code for ``inv_prod``:
https://www.cvxpy.org/_modules/cvxpy/atoms/inv_prod.html
Try replacing ``inv_prod`` with the linked code and make sure the second argument to power is of type ``int64``.

**Comment by aengl5337** [comment]
Fantastic, on to the next bug!  Thank you!!!
