### ISSUE TITLE
Exception raised when initialising integer variable whose shape is a list

### ISSUE THREAD

**Issue by jakelevi1996** [cvxpy/cvxpy#1921]
**Describe the bug**

Exception raised when initialising integer variable whose shape is a list. If I 

**To Reproduce**

```python
import cvxpy as cp

x = cp.Variable(shape=[9*9*9], integer=True)
```

Output:

```
Traceback (most recent call last):

...

  File "C:\Program Files\Python37\lib\site-packages\cvxpy\expressions\variable.py", line 86, in __init__
    super(Variable, self).__init__(shape, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\cvxpy\expressions\leaf.py", line 133, in __init__
    np.ndindex(max(shape, (1,))))
TypeError: '>' not supported between instances of 'tuple' and 'list'
```

Easily fixed:

```python
x = cp.Variable(shape=(9*9*9), integer=True)
```

**Expected behavior**

Either no exception, or a helpful `cvxpy` exception explaining why a `Variable` can't have the shape specified as a list

**Output**

Included above

**Version**
 - OS:  Windows 10
 - CVXPY Version:

```
$ python -m pip show cvxpy
Name: cvxpy
Version: 1.2.1
Summary: A domain-specific language for modeling convex optimization problems in Python.
Home-page: https://github.com/cvxpy/cvxpy
Author: Steven Diamond, Eric Chu, Stephen Boyd
Author-email: stevend2@stanford.edu, akshayka@cs.stanford.edu, echu508@stanford.edu, boyd@stanford.edu
License: Apache License, Version 2.0
Location: c:\program files\python37\lib\site-packages
Requires: ecos, numpy, osqp, scipy, scs
Required-by:
```

**Additional context**

None

**Comment by phschiele** [comment]
Thanks for reporting, even thought you find a fix for your case.
My inclination would be to fix this, as e.g. `np.zeros([2,3])` also works.

**Comment by SteveDiamond** [comment]
Fixed in master.
