### ISSUE TITLE
Tuple out of range error on Maximize

### ISSUE THREAD

**Issue by orgershoni** [cvxpy/cvxpy#2027]
**Describe the bug**
I'm trying to maximize a concave function using the package. During canonicalization, I get some runtime errors and the program fails
**To Reproduce**
```python
  M = np.array([  
  [1, 1, 0, 0, 0, 1, 1], 
  [1, 0, 1, 0, 1, 0, 1],
  [1, 0, 0, 1, 1, 1, 0]
  ])
  
  P = [0.99249786, 0.4105009,  0.03501452]
  
  O = [1, 3.00730045, 3.61390616, 2.53630693, 2.16152629, 3.63182933, 1.75637617]
  
  MO = M * O
  
  options_num = len(M[0])
  lower_bound = np.zeros(options_num)
  upper_bound = np.ones(options_num)
  
  x = cp.Variable(shape=(options_num,), nonneg=True, name="x")

  inner_multi = MO @ x
  inner_sum = cp.sum(inner_multi, axis=1)
  log_sum = cp.log(inner_sum)
  obj = cp.scalar_product(P, log_sum)
  objective = cp.Maximize(obj)
  constraints = [lower_bound <= x, x <= upper_bound, cp.sum(x) == 1]
  problem = cp.Problem(objective, constraints)
  
  print(problem)
  result = problem.solve(verbose=True)
  print(x.value)
```

**Expected behavior**
I expect the optimization to run smoothly

**Output**
```bash
maximize Sum(conj(Hstack(reshape(0.99249786, (1,), F), reshape(0.4105009, (1,), F), reshape(0.03501452, (1,), F))) @ log(Sum([[1.         3.00730045 0.         0.         0.         3.63182933
  1.75637617]
 [1.         0.         3.61390616 0.         2.16152629 0.
  1.75637617]
 [1.         0.         0.         2.53630693 2.16152629 3.63182933
  0.        ]] @ x, 1, False)), None, False)
subject to [0. 0. 0. 0. 0. 0. 0.] <= x
           x <= [1. 1. 1. 1. 1. 1. 1.]
           Sum(x, None, False) == 1.0
===============================================================================
                                     CVXPY                                     
                                     v1.3.0                                    
===============================================================================
(CVXPY) Jan 28 02:05:04 PM: Your problem has 7 variables, 3 constraints, and 0 parameters.
(CVXPY) Jan 28 02:05:04 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jan 28 02:05:04 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jan 28 02:05:04 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Jan 28 02:05:04 PM: Compiling problem (target solver=MOSEK).
(CVXPY) Jan 28 02:05:04 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> MOSEK
(CVXPY) Jan 28 02:05:04 PM: Applying reduction FlipObjective
(CVXPY) Jan 28 02:05:04 PM: Applying reduction Dcp2Cone
(CVXPY) Jan 28 02:05:04 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jan 28 02:05:04 PM: Applying reduction ConeMatrixStuffing
Traceback (most recent call last):
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/utilities/performance_utils.py", line 37, in _lazyprop
    return getattr(self, attr_name)
AttributeError: 'Sum' object has no attribute '_lazy_canonical_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cvxpy_try.py", line 93, in <module>
    example()
  File "cvxpy_try.py", line 83, in example
    result = problem.solve(verbose=True)
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 493, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1054, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 681, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 354, in apply
    params_to_problem_data = extractor.affine(expr_list)
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/utilities/coeff_extractor.py", line 83, in affine
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/utilities/coeff_extractor.py", line 83, in <listcomp>
    op_list = [e.canonical_form[0] for e in expr_list]
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/utilities/performance_utils.py", line 39, in _lazyprop
    setattr(self, attr_name, func(self))
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/utilities/canonical.py", line 43, in canonical_form
    return self.canonicalize()
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/atoms/atom.py", line 327, in canonicalize
    graph_obj, graph_constr = self.graph_implementation(arg_objs,
  File "/home/dutzi/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/sum.py", line 93, in graph_implementation
    const_shape = (arg_objs[0].shape[1],)
IndexError: tuple index out of range
```

**Version**
 - OS: Ubunto 22
 - CVXPY Version: 1.3

**Comment by orgershoni** [comment]
Duplicated with the `cp.sum(axis=1)` on 1D array issue
