### ISSUE TITLE
cannot disable some cut generators for CBC via options

### ISSUE THREAD

**Issue by sdementen** [cvxpy/cvxpy#2037]
According to my understanding of the docs https://www.cvxpy.org/tutorial/advanced/index.html for the CBC options, I would expect to be able to disable some cut generations via the code below yet I get an exception:
```python
problem.solve(
    solver="CBC",
    KnapsackCuts=False,
    CliqueCuts=False,
    FlowCoverCuts=False,
    ZeroHalfCuts=False,
) 
```

**To Reproduce**
```python
import cvxpy as cp

x = cp.Variable(integer=True)

problem = cp.Problem(objective=cp.Maximize(x), constraints=[x <= 0])

problem.solve(
    solver="CBC",
    verbose=True,
    KnapsackCuts=False,
    CliqueCuts=False,
    FlowCoverCuts=False,
    ZeroHalfCuts=False,
)
```

**Expected behavior**
Solve the problem using CBC with the specific cut strategies disabled.

**Output**
```python
Traceback (most recent call last):
  File "...\cvxpycbcoptionsfail.py", line 7, in <module>
    problem.solve(
  File "...\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "...\lib\site-packages\cvxpy\problems\problem.py", line 1016, in _solve
    solution = solving_chain.solve_via_data(
  File "...\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 361, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "...\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\cbc_conif.py", line 167, in solve_via_data
    setattr(cbcModel, key, value)
AttributeError: 'cylp.cy.CyCbcModel.CyCbcModel' object has no attribute 'KnapsackCuts'
```

**Version**
 - OS:  windows 10
 - CVXPY Version: 1.2.2

**Comment by SteveDiamond** [comment]
You should study the ``cylp`` package and the options it supports. It may not be the same set as the Cbc binary. Concretely, the cvxpy interface runs the following code:
```
  model = CyLPModel()
  ...
  model = CyClpSimplex(model)
  ...
  cbcModel = model.getCbcModel()
  for key, value in solver_opts.items():
      setattr(cbcModel, key, value)
```
so you can look at what CyCbcModels support.

**Comment by rileyjmurray** [comment]
Related to (and possibly resolved by) #1821.
