### ISSUE TITLE
Cannot import name 'glpk' from 'cvxopt' on ARM. 

### ISSUE THREAD

**Issue by DigitalGabriele** [cvxpy/cvxpy#2243]
I have a file that I was able to run on my Mac that has M1 chip. I am current trying to run the code on a Jetson tx1. 
I have installed  CVXPY to run on ARM computer:

`pip install cvxopt`

result:
```
Collecting cvxopt
  Using cached cvxopt-1.3.2.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cvxopt
  Building wheel for cvxopt (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cvxopt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-37
      creating build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/__init__.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/info.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/_version.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/msk.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/cvxprog.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/misc.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/coneprog.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/modeling.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/solvers.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      copying src/python/printing.py -> build/lib.linux-aarch64-cpython-37/cvxopt
      running build_ext
      building 'base' extension
      creating build/temp.linux-aarch64-cpython-37
      creating build/temp.linux-aarch64-cpython-37/src
      creating build/temp.linux-aarch64-cpython-37/src/C
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/base.c -o build/temp.linux-aarch64-cpython-37/src/C/base.o
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/dense.c -o build/temp.linux-aarch64-cpython-37/src/C/dense.o
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/sparse.c -o build/temp.linux-aarch64-cpython-37/src/C/sparse.o
      gcc -pthread -shared -B /home/ubuntu/c4aarch64_installer/compiler_compat -L/home/ubuntu/c4aarch64_installer/lib -Wl,-rpath=/home/ubuntu/c4aarch64_installer/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-aarch64-cpython-37/src/C/base.o build/temp.linux-aarch64-cpython-37/src/C/dense.o build/temp.linux-aarch64-cpython-37/src/C/sparse.o -L/usr/lib -lm -llapack -lblas -o build/lib.linux-aarch64-cpython-37/cvxopt/base.cpython-37m-aarch64-linux-gnu.so
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../.." is unsafe for cross-compilation
      building 'blas' extension
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/blas.c -o build/temp.linux-aarch64-cpython-37/src/C/blas.o
      gcc -pthread -shared -B /home/ubuntu/c4aarch64_installer/compiler_compat -L/home/ubuntu/c4aarch64_installer/lib -Wl,-rpath=/home/ubuntu/c4aarch64_installer/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-aarch64-cpython-37/src/C/blas.o -L/usr/lib -lblas -o build/lib.linux-aarch64-cpython-37/cvxopt/blas.cpython-37m-aarch64-linux-gnu.so
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../.." is unsafe for cross-compilation
      building 'lapack' extension
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/lapack.c -o build/temp.linux-aarch64-cpython-37/src/C/lapack.o
      gcc -pthread -shared -B /home/ubuntu/c4aarch64_installer/compiler_compat -L/home/ubuntu/c4aarch64_installer/lib -Wl,-rpath=/home/ubuntu/c4aarch64_installer/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-aarch64-cpython-37/src/C/lapack.o -L/usr/lib -llapack -lblas -o build/lib.linux-aarch64-cpython-37/cvxopt/lapack.cpython-37m-aarch64-linux-gnu.so
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../../../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/aarch64-linux-gnu" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
      /home/ubuntu/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-linux-gnu/7/../../.." is unsafe for cross-compilation
      building 'umfpack' extension
      gcc -pthread -B /home/ubuntu/c4aarch64_installer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/home/ubuntu/c4aarch64_installer/include/python3.7m -c src/C/umfpack.c -o build/temp.linux-aarch64-cpython-37/src/C/umfpack.o
      src/C/umfpack.c:23:10: fatal error: umfpack.h: No such file or directory
       #include "umfpack.h"
                ^~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cvxopt
Failed to build cvxopt
ERROR: Could not build wheels for cvxopt, which is required to install pyproject.toml-based projects
```

I then found a solution online to this and did:
```
 wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz

 tar -xf SuiteSparse-4.5.3.tar.gz SuiteSparse/

 export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse
```

Then I ran again `pip install cvxopt` and got an error running my code `ModuleNotFoundError: No module named 'cvxpy'
`

So I ran: `pip install cvxpy` and `sudo apt-get install glpk-utils`

I am currently getting:

```
(CVXPY) Oct 02 04:57:33 PM: Encountered unexpected exception importing solver GLPK:
ImportError("cannot import name 'glpk' from 'cvxopt' (/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxopt/__init__.py)")

Traceback (most recent call last):
  File "untitled12.py", line 54, in <module>
    route = vrp_solver.solve_model()
  File "untitled12.py", line 38, in solve_model
    prob.solve(solver=cp.GLPK_MI)  # Use the GLPK MIP solver
  File "/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 495, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 1057, in _solve
    solver, gp, enforce_dpp, ignore_dpp, verbose, canon_backend, kwargs
  File "/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 638, in get_problem_data
    solver_opts=solver_opts)
  File "/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 883, in _construct_chain
    candidate_solvers = self._find_candidate_solvers(solver=solver, gp=gp)
  File "/home/ubuntu/c4aarch64_installer/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 746, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver GLPK_MI is not installed.
```

I understand it's a cvxpy GitHub, but maybe someone knows how to solve it.

**Comment by SteveDiamond** [comment]
cvxopt and cvxpy are different packages :P You are trying to install cvxopt, not cvxpy.

**Comment by DigitalGabriele** [comment]
I am really desperate :D Deleting the post.

**Comment by DigitalGabriele** [comment]
Wrong repo.
