### ISSUE TITLE
Unable to concatenate a cp.Variable vector

### ISSUE THREAD

**Issue by antonelloventurino** [cvxpy/cvxpy#2328]
**Describe the bug**
I'm trying to make an LMI constraint like:

[[scalar, variable2D'],
[variable2D, identity2D]] >>0

but is impossible due to the fact that the solver does not concatenate the elements. The entire matrix at the end has a shape = (2,2) and not (3,3) as expected. 

**To Reproduce**
```
import cvxpy as cp
import numpy as np

# scalar
u = 3
# variable
x = cp.Variable(2)
c_vert = cp.vstack([u, x])
```

**Expected behavior**
`c_vert` must be a vector with 3 elements. First one as known scalar and second ones from `x` variable vector.

**Output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/vstack.py", line 29, in vstack
    return Vstack(*arg_list)
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/atom.py", line 50, in __init__
    self.validate_arguments()
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/vstack.py", line 74, in validate_arguments
    raise ValueError(("All the input dimensions except"
ValueError: All the input dimensions except for axis 0 must match exactly.
```

**Version**
 - OS: Linux Ubuntu 20.04
 - CVXPY Version: 1.4.1

**Comment by SteveDiamond** [comment]
This is not a big. The behavior is the same as numpy. Try using the bmat function and make all elements 2 dimensional. For example, scalar = np.ones((1,1)) * value

**Comment by antonelloventurino** [comment]
> This is not a bug. The behavior is the same as numpy. Try using the bmat function and make all elements 2 dimensional. For example, scalar = np.ones((1,1)) * value

Thanks, it works this way. However, just for information, numpy is a bit smarter.
Example 1 with cvxpy gives an error:
```
import cvxpy as cp
import numpy as np
U = cp.Variable(shape=(2,1))
u_bounds_max=2
cp.bmat([[ u_bounds_max ** 2, U.T], [U, cp.bmat(np.identity(2))]])
```
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/bmat.py", line 37, in bmat
    row_blocks = [hstack(blocks) for blocks in block_lists]
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/bmat.py", line 37, in <listcomp>
    row_blocks = [hstack(blocks) for blocks in block_lists]
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/hstack.py", line 38, in hstack
    return Hstack(*arg_list)
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/atom.py", line 50, in __init__
    self.validate_arguments()
  File "/home/*/.local/lib/python3.8/site-packages/cvxpy/atoms/affine/hstack.py", line 68, in validate_arguments
    raise error
ValueError: All the input dimensions except for axis 1 must match exactly.
```

Same example with numpy works fine:
```
import numpy as np
U = np.ones((2,1))
u_bounds_max=2
np.block([[u_bounds_max ** 2, U.T], [U, np.identity(2)]])
```
Output correct:
```
array([[4., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

**Comment by SteveDiamond** [comment]
That's good to know. We will make it work in cvxpy then.

**Comment by SteveDiamond** [comment]
For reference ``numpy.bmat`` does not handle scalars gracefully like ``numpy.block``.

**Comment by rileyjmurray** [comment]
bmat also returns a matrix object and not an ndarray, so will probably be
discouraged moving forward. It would be prudent for us to make an analog of
NumPy’s block function.

**Comment by Transurgeon** [comment]
https://github.com/cvxpy/cvxpy/issues/2752 this is a related issue.

**Comment by enzo-boulin** [comment]
I've opened a PR for this (#3466). Promoting scalar/1-D blocks in bmat to match numpy.block. Happy to adjust the approach if you'd prefer a separate cp.block function instead.
