### ISSUE TITLE
Adverse interaction between multiprocessing.Pool and cvxpy PSD constraints

### ISSUE THREAD

**Issue by JBurniston** [cvxpy/cvxpy#2366]
**Describe the bug**
Starting from a fresh python kernel, solving a problem in a parallel pools throws `ValueError: row index exceeds matrix dimensions` from scipy in \cvxpy\cvxcore\python\canonInterface.py line 382. However, running the same file again will no longer cause the error and the program will execute on the parallel pool as normal.

**To Reproduce**
From a fresh kernel, run the following minimal working example:
```Python
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  2 14:45:25 2024
"""

import numpy as np
import cvxpy as cp

from multiprocessing import Pool
from functools import partial


def main():
    
    x = cp.Variable([3,3],hermitian=True)
    y = cp.Variable([3,3],nonneg=True)
    objVec = cp.Parameter([3,1])
    
    objective = cp.Minimize(y[0,:]@objVec)
    
    constraints = [x>>0]
    
    prblm = cp.Problem(objective,constraints)
    
    assert prblm.is_dcp(dpp=True)
    
    
    pool = Pool(processes=1)
    
    partialFunc = partial(runProblem,prblm=prblm,objVec=objVec)
    
    results = pool.map(partialFunc,range(3))
    
    print(results)
    


def runProblem(index,prblm,objVec):
    
    vec = np.zeros([3,1])
    vec[index,0] = 1
    
    objVec.value = vec
    prblm.solve(solver="SCS")
    
    return prblm.value
    
    

if __name__ == "__main__":
    main()
```

**Expected behavior**
The pool executes each run of the parameterized problem in the pool like it does on the second run.

**Output**
Console and stack trace (person detail removed):
```
Python 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 8.12.0 -- An enhanced Interactive Python.

runfile('~~~/parallelError.py', wdir='~~~')
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "~~~\.conda\envs\QuantumInfo\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "~~~\.conda\envs\QuantumInfo\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "~~~\\parallelerror.py", line 44, in runProblem
    prblm.solve(solver="SCS")
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\problems\problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\problems\problem.py", line 1072, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\problems\problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\reductions\chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\reductions\dcp2cone\cone_matrix_stuffing.py", line 368, in apply
    params_to_problem_data = extractor.affine(expr_list)
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 99, in affine
    return canonInterface.get_problem_matrix(op_list,
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 382, in get_problem_matrix
    A = sp.csc_matrix(
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\scipy\sparse\_compressed.py", line 53, in __init__
    self._coo_container(arg1, shape=shape, dtype=dtype)
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\scipy\sparse\_coo.py", line 197, in __init__
    self._check()
  File "~~~\.conda\envs\QuantumInfo\lib\site-packages\scipy\sparse\_coo.py", line 284, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File ~\.conda\envs\QuantumInfo\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~~~\\parallelerror.py:51
    main()

  File ~~~\\parallelerror.py:32 in main
    results = pool.map(partialFunc,range(3))

  File ~\.conda\envs\QuantumInfo\lib\multiprocessing\pool.py:367 in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File ~\.conda\envs\QuantumInfo\lib\multiprocessing\pool.py:774 in get
    raise self._value

ValueError: row index exceeds matrix dimensions


runfile('~~~/parallelError.py', wdir='~~~')
[9.488123512395584e-06, 9.488123512395584e-06, 9.488123512395584e-06]
```

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.4.2
 - Python 3.10.11
 - Spyder 5.4.3

**Additional context**
Removing the constraint `x>>0` prevents the bug. Running a different CVXPY problem first also seems to prevent the bug. Restarting the module causes the error to occur again on the next run or causes python to hang.

**Comment by phschiele** [comment]
Hi @JBurniston,

CVXPY is not thread safe, see 
https://github.com/cvxpy/cvxpy/issues/1021
https://github.com/cvxpy/cvxpy/issues/1602

Can you try with Dask as suggested in the issue and see if it works?
