### ISSUE TITLE
Take the derivative of the unknown variables

### ISSUE THREAD

**Issue by fine4303** [cvxpy/cvxpy#2404]
hello!

There is an expression containing unknown variables, and I wish to use the derivative of this expression with respect to one of its variables as the objective function for convex optimization(I can ensure that the problem satisfies DCP).

However, CVXPY seems unable to recognize the `sp.Heaviside()` function.
Does CVXPY have any available APIs for differentiation?

my code:
```
import sympy as sp
import cvxpy as cp

x, y = sp.symbols('x y')
expr = x**2 + 3*x + x*y + sp.Max(0, 2*x*y + x**2)

deriv_expr_x = sp.diff(expr, x)
print(deriv_expr_x)  # 2*x + y + (2*x + 2*y)*Heaviside(x**2 + 2*x*y) + 3
deriv_func = sp.lambdify([x, y], deriv_expr_x)

x_cvxpy = cp.Variable()
objective = cp.Minimize(deriv_func(x_cvxpy, 1))
problem = cp.Problem(objective, [x_cvxpy >= 0])
problem.solve()
```

Output:
```
Traceback (most recent call last):
  File "D:\PycharmProjects\test.py", line 451, in <module>
    objective = cp.Minimize(deriv_func(x_cvxpy, 1))
  File "<lambdifygenerated-1>", line 2, in _lambdifygenerated
  File "D:\anaconda3\envs\invODE\lib\site-packages\cvxpy\expressions\expression.py", line 749, in __array_ufunc__
    raise RuntimeError(__NUMPY_UFUNC_ERROR__)
RuntimeError: 
You're calling a NumPy function on a CVXPY expression. This is prone to causing
errors or code that doesn't behave as expected. Consider using one of the
functions documented here: https://www.cvxpy.org/tutorial/functions/index.html
```

Any help would be appreciated!

**Comment by SteveDiamond** [comment]
CVXPY does not use gradient based solvers, so it cannot use functions that provide a gradient oracle.
