### ISSUE TITLE
Index exceeds matrix dimension when solving a simple quadratic programming model

### ISSUE THREAD

**Issue by metab0t** [cvxpy/cvxpy#2466]
**Describe the bug**
Cvxpy errors when solving a simple model

**To Reproduce**
```python
import numpy as np
import cvxpy


def create_problem(N):
    x = cvxpy.Variable((N, N))
    y = cvxpy.Variable((N, N))
    constraints = []
    for i in range(N):
        constraints.append(x[:, i] - y[:, i] >= np.arange(N))
    constraints.append(x + y >= 0)
    objective = cvxpy.Minimize(cvxpy.sum_squares(x) + cvxpy.sum(y))
    return cvxpy.Problem(objective, constraints)


N = 200

model = create_problem(N)
model.solve(solver=cvxpy.CLARABEL)

```

**Expected behavior**
Solve the problem correctly.

**Output**
```
Traceback (most recent call last):
  File "E:\codeworkspace\cvxpy_debug.py", line 19, in <module>
    model.solve(solver=cvxpy.CLARABEL)
  File "D:\mambaforge\Lib\site-packages\cvxpy\problems\problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\problems\problem.py", line 1073, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\problems\problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\reductions\chain.py", line 76, in apply
    problem, inv = r.apply(problem)
                   ^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\reductions\dcp2cone\cone_matrix_stuffing.py", line 346, in apply
    params_to_P, params_to_c, flattened_variable = self.stuffed_objective(
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\reductions\dcp2cone\cone_matrix_stuffing.py", line 333, in stuffed_objective
    params_to_P, params_to_c = extractor.quad_form(expr)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 263, in quad_form
    P = self.merge_P_list(P_list, P_height, num_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 304, in merge_P_list
    return combined.flatten_tensor(num_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\cvxpy\lin_ops\canon_backend.py", line 112, in flatten_tensor
    return sp.csc_matrix((self.data, (rows, cols)), shape=shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\scipy\sparse\_compressed.py", line 55, in __init__
    coo = self._coo_container(arg1, shape=shape, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mambaforge\Lib\site-packages\scipy\sparse\_coo.py", line 99, in __init__
    self._check()
  File "D:\mambaforge\Lib\site-packages\scipy\sparse\_coo.py", line 205, in _check
    raise ValueError(f'axis {i} index {idx.max()} exceeds '
ValueError: axis 0 index 3199959999 exceeds matrix dimension 2105032704
```

**Version**
 - OS: Windows
 - CVXPY Version: 1.5.1

**Additional context**

**Comment by metab0t** [comment]
Has been fixed by https://github.com/cvxpy/cvxpy/pull/2461
