### ISSUE TITLE
Getting int32 overflows when trying to solve a simple SDP on 100 x 100 matrices

### ISSUE THREAD

**Issue by mkdeak** [cvxpy/cvxpy#2512]
**Describe the bug**
An int32 overflow is thrown when I run `prob.solve()` on a stripped down SDP involving matrices of size 100 x 100.

**To Reproduce**
```
import cvxpy as cp
import numpy as np

# size params
N = 200
k = 4

I = np.eye(N // 2)
J = np.fliplr(I)
A = [[] for _ in range(k + 1)]
B = [[] for _ in range(k + 1)]

constraints = []
for i in range(1, k):
    A[i] = cp.Variable((N // 2, N // 2), symmetric=True)
    B[i] = cp.Variable((N // 2, N // 2))
    
    constraints += [J @ B[i].T @ J == B[i]]

    constraints += [A[i] + B[i] @ J >> 0]
    constraints += [A[i] - B[i] @ J >> 0]

prob = cp.Problem(cp.Minimize(0), constraints)
prob.solve(eps=10**-6, solver=cp.MOSEK, verbose=True)
```

**Expected behavior**
No overflow exceptions are thrown. 

**Output**
```
===============================================================================
                                     CVXPY                                     
                            v1.6.0.dev0+113.09f9a37                            
===============================================================================
(CVXPY) Jul 23 04:12:49 PM: Your problem has 60000 variables, 90000 constraints, and 0 parameters.
(CVXPY) Jul 23 04:12:49 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 23 04:12:49 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 23 04:12:49 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 23 04:12:49 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Jul 23 04:12:49 PM: Compiling problem (target solver=MOSEK).
(CVXPY) Jul 23 04:12:49 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> MOSEK
(CVXPY) Jul 23 04:12:49 PM: Applying reduction Dcp2Cone
(CVXPY) Jul 23 04:12:49 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 23 04:12:49 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 23 04:12:49 PM: Applying reduction MOSEK
Traceback (most recent call last):
  File "/Users/myuser/mcve.py", line 24, in <module>
    prob.solve(eps=10**-6, solver=cp.MOSEK, verbose=True)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/problems/problem.py", line 573, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/problems/problem.py", line 1143, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/problems/problem.py", line 766, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py", line 239, in apply
    data, inv_data = Dualize.apply(problem)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/reductions/cone2cone/affine2direct.py", line 96, in apply
    c, d, A, b = problem.apply_parameters()
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 201, in apply_parameters
    self.reduced_A.cache(keep_zeros)
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/reductions/utilities.py", line 141, in cache
    canonInterface.reduce_problem_data_tensor(
  File "/Users/myuser/Library/Python/3.9/lib/python/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 130, in reduce_problem_data_tensor
    n_constr = A.shape[0] // (n_cols)
OverflowError: Python integer 2722605300 out of bounds for int32
```

**Version**
 - OS: MacOS Sonoma 14.5, Apple Silicon 
 - CVXPY Version: 1.6.0 

**Additional context**
May be related to https://github.com/cvxpy/cvxpy/pull/2461

**Comment by Transurgeon** [comment]
Hey @mkdeak thanks for raising this issue!
I believe we might have fixed this error in the following PR: https://github.com/cvxpy/cvxpy/pull/2509
could you try building cvxpy from master again and run your code?

**Comment by mkdeak** [comment]
Yes, @Transurgeon, I could not reproduce after reinstalling from master. Thanks for having a look for me.
