### ISSUE TITLE
Overflow errors on the problem shape

### ISSUE THREAD

**Issue by chrizandrcouture** [cvxpy/cvxpy#2522]
**Describe the bug**
I'm trying to run an optimisation problem for warehouse routing. [link](https://purehost.bath.ac.uk/ws/portalfiles/portal/227399764/Inventory_routing_in_a_warehouse_The_storage_replenishment_routing_problem.pdf)

I implemented the whole paper in CVXPY over [here](https://github.com/chrizandr/warehouse/blob/main/optim.py)

I keep running into overflow errors on the shape of my variables or constraints.

My question is whether this is a limitation imposed on purpose on these solvers? Is there no way for me to run big optimisation problems like this (3172980 variables, 48301 constraints) in CVXPY.

Can I somehow reduce the number of constraints?

Any help would be appreciated.

**To Reproduce**
clone the repo here : [here](https://github.com/chrizandr/warehouse)
Run optim.py after installing all dependencies in requirements.txt [change the path for the input file appropriately]

**Expected behavior**

**Output**
```
===============================================================================
                                     CVXPY
                                     v1.5.2
===============================================================================
(CVXPY) Aug 01 07:37:29 AM: Your problem has 3172980 variables, 48301 constraints, and 0 parameters.
(CVXPY) Aug 01 07:37:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Aug 01 07:37:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Aug 01 07:37:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Aug 01 07:37:44 AM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
(CVXPY) Aug 01 07:38:02 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Aug 01 07:38:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> GLPK_MI
(CVXPY) Aug 01 07:38:02 AM: Applying reduction Dcp2Cone
(CVXPY) Aug 01 07:40:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Aug 01 07:40:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Aug 01 10:05:37 AM: Applying reduction GLPK_MI
Traceback (most recent call last):
  File "/home/ubuntu/warehouse/optim.py", line 432, in <module>
    optim = SRRP(dataset)
  File "/home/ubuntu/warehouse/optim.py", line 173, in __init__
    self.solve(objective, constraints, vars, intermediate_vars)
  File "/home/ubuntu/warehouse/optim.py", line 419, in solve
    problem.solve(solver=solver, verbose=True)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1073, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py", line 46, in apply
    data, inv_data = super(GLPK_MI, self).apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py", line 114, in apply
    c, d, A, b = problem.apply_parameters()
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 201, in apply_parameters
    self.reduced_A.cache(keep_zeros)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/utilities.py", line 141, in cache
    canonInterface.reduce_problem_data_tensor(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 130, in reduce_problem_data_tensor
    n_constr = A.shape[0] // (n_cols)
OverflowError: Python integer 153258155281 out of bounds for int32
```

Before this I encountered problems in the conic_solver, I fixed that by casting the shape in divmod to int64 instead.
```
===============================================================================
                                     CVXPY
                                     v1.5.2
===============================================================================
(CVXPY) Jul 30 11:49:23 AM: Your problem has 3172980 variables, 48301 constraints, and 0 parameters.
(CVXPY) Jul 30 11:49:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 30 11:49:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 30 11:49:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 30 11:49:38 AM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
(CVXPY) Jul 30 11:49:55 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Jul 30 11:49:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> GLPK_MI
(CVXPY) Jul 30 11:49:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 30 11:52:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 30 11:52:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 30 02:16:59 PM: Applying reduction GLPK_MI
Traceback (most recent call last):
  File "/home/ubuntu/warehouse/optim.py", line 431, in <module>
    # )
  File "/home/ubuntu/warehouse/optim.py", line 173, in __init__
    self.solve(objective, constraints, vars, intermediate_vars)
  File "/home/ubuntu/warehouse/optim.py", line 419, in solve
    problem.solve(solver=solver, verbose=True)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1073, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 696, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/chain.py", line 76, in apply
    problem, inv = r.apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py", line 46, in apply
    data, inv_data = super(GLPK_MI, self).apply(problem)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py", line 104, in apply
    problem = self.format_constraints(problem, None)
  File "/home/ubuntu/warehouse/venv/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 264, in format_constraints
    unspecified, remainder = divmod(problem.A.shape[0] *
OverflowError: Python integer 153258155281 out of bounds for int32
```
**Version**
 - OS: Ubuntu
 - CVXPY Version: 1.5.2

**Additional context**

**Comment by SteveDiamond** [comment]
Can you try installing from master?

**Comment by GonzagueHenri** [comment]
Hello, I ran into a similar issue (cf below), using CVXPY 1.6 and 1.7 (from main), I got it resolved by downgrading scipy from 1.15 to 1.14.1

 `
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/cbc_conif.py:88, in CBC.apply(self, problem)
     80 def apply(self, problem):
     81     """Returns a new problem and data for inverting the new solution.
     82 
     83     Returns
   (...)
     86         (dict of arguments needed for the solver, inverse data)
     87     """
---> 88     data, inv_data = super(CBC, self).apply(problem)
     89     variables = problem.x
     90     data[s.BOOL_IDX] = [int(t[0]) for t in variables.boolean_idx]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py:355, in ConicSolver.apply(self, problem)
    344 """Returns a new problem and data for inverting the new solution.
    345 
    346 Returns
   (...)
    349     (dict of arguments needed for the solver, inverse data)
    350 """
    352 # This is a reference implementation following SCS conventions
    353 # Implementations for other solvers may amend or override the implementation entirely
--> 355 problem, data, inv_data = self._prepare_data_and_inv_data(problem)
    357 # Apply parameter values.
    358 # Obtain A, b such that Ax + s = b, s \in cones.
    359 if problem.P is None:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py:332, in ConicSolver._prepare_data_and_inv_data(self, problem)
    321 # Format constraints
    322 #
    323 # By default cvxpy follows the SCS convention, which requires
   (...)
    329 # 5. exponential
    330 # 6. three-dimensional power cones
    331 if not problem.formatted:
--> 332     problem = self.format_constraints(problem, self.EXP_CONE_ORDER)
    333 data[s.PARAM_PROB] = problem
    334 data[self.DIMS] = problem.cone_dims

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py:274, in ConicSolver.format_constraints(cls, problem, exp_cone_order)
    272     restructured_A.row = restructured_A.row.astype(np.int64)
    273     restructured_A.col = restructured_A.col.astype(np.int64)
--> 274     restructured_A = restructured_A.reshape(
    275         np.int64(restruct_mat.shape[0]) * (np.int64(problem.x.size) + 1),
    276         problem.A.shape[1], order='F')
    277 else:
    278     restructured_A = problem.A

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/scipy/sparse/_coo.py:161, in _coo_base.reshape(self, *args, **kwargs)
    158 else:
    159     new_data = self.data
--> 161 return self.__class__((new_data, new_coords), shape=shape, copy=False)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/scipy/sparse/_coo.py:101, in _coo_base.__init__(self, arg1, shape, dtype, copy, maxprint)
     98 if len(self._shape) > 2:
     99     self.coords = tuple(idx.astype(np.int64, copy=False) for idx in self.coords)
--> 101 self._check()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-108f4c5f-6ed8-4dfb-857f-2393b623ab64/lib/python3.10/site-packages/scipy/sparse/_coo.py:225, in _coo_base._check(self)
    222     raise ValueError(f'axis {i} index {idx.max()} exceeds '
    223                      f'matrix dimension {self.shape[i]}')
    224 if idx.min() < 0:
--> 225     raise ValueError(f'negative axis {i} index: {idx.min()}')

ValueError: negative axis 0 index: -2147469654
`

**Comment by Transurgeon** [comment]
closing this issue since it has been resolved
