### ISSUE TITLE
CLARABEL raises SolverError on a basic SOCP when SCS and ECOS doesn't

### ISSUE THREAD

**Issue by cahity** [cvxpy/cvxpy#2610]
**Describe the bug**
When I run the code given below, I get a solver failed error. I encountered this problem during the execution of a different program and stilled it down to this basic state. Float values are key but I don't quite understand why.

**To Reproduce**
```python
def simple_SOCP():
    vi = np.array([0.0, 0.5986520274656673])
    vj = np.array([0.0, 1.2438926041619276])
    x = cp.Variable(2)

    soc_constraint = [cp.SOC(0.1, (np.eye(2) @ x) + (vi - vj))]
    prob = cp.Problem(cp.Minimize(0), soc_constraint)

    prob.solve()
    # prob.solve(solver=cp.SCS)

    return x.value is not None
```

**Expected behavior**
When I run the same code with SCS or ECOS, I get a solution though they are contradictory with each other. I don't know which is correct.

**Output**
```
(torch) cahit@server_name:~/works/project_name$ python clarabel_error.py
===============================================================================                                                                                                              
                                     CVXPY                                                                                                                                                   
                                     v1.5.3                                                                                                                                                  
===============================================================================                                                                                                              
(CVXPY) Nov 01 03:19:07 PM: Your problem has 2 variables, 1 constraints, and 0 parameters.                                                                                                   
(CVXPY) Nov 01 03:19:07 PM: It is compliant with the following grammars: DCP, DQCP                                                                                                           
(CVXPY) Nov 01 03:19:07 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)                                                          
(CVXPY) Nov 01 03:19:07 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.                                                             
(CVXPY) Nov 01 03:19:07 PM: Your problem is compiled with the CPP canonicalization backend.                                                                                                  
-------------------------------------------------------------------------------                                                                                                              
                                  Compilation                                                                                                                                                
-------------------------------------------------------------------------------                                                                                                              
(CVXPY) Nov 01 03:19:07 PM: Compiling problem (target solver=CLARABEL).                                                                                                                      
(CVXPY) Nov 01 03:19:07 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> CLARABEL                                                                                    
(CVXPY) Nov 01 03:19:07 PM: Applying reduction Dcp2Cone                                                                                                                                      
(CVXPY) Nov 01 03:19:07 PM: Applying reduction CvxAttr2Constr                                                                                                                                
(CVXPY) Nov 01 03:19:07 PM: Applying reduction ConeMatrixStuffing                                                                                                                            
(CVXPY) Nov 01 03:19:07 PM: Applying reduction CLARABEL                                                                                                                                      
(CVXPY) Nov 01 03:19:07 PM: Finished problem compilation (took 2.257e-03 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Nov 01 03:19:07 PM: Invoking solver CLARABEL  to obtain a solution.
-------------------------------------------------------------
           Clarabel.rs v0.7.1  -  Clever Acronym              

                   (c) Paul Goulart                           
                University of Oxford, 2022                    
-------------------------------------------------------------

problem:
  variables     = 2
  constraints   = 3
  nnz(P)        = 0
  nnz(A)        = 2
  cones (total) = 1
    : SecondOrder = 1,  numel = 3

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 200, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-5, max_scale = 1.0e5
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0  +0.0000e+00  -1.0000e-01  1.00e-01  3.93e-01  0.00e+00  1.00e+00  1.00e+00   ------   
  1  +0.0000e+00  -7.0245e-02  7.02e-02  4.44e-02  6.41e-18  8.66e-03  8.28e-02  9.18e-01  
  2  +0.0000e+00  +4.0421e-04  4.04e-04  1.53e-03  5.83e-18  3.01e-03  4.32e-03  9.90e-01  
---------------------------------------------------------------------------------------------
Terminated with status = NumericalError
solve time = 22.358µs
Traceback (most recent call last):
  File "/home/cahit/works/project_name/clarabel_error.py", line 51, in <module>
    print(simple_SOCP())
  File "/home/cahit/works/project_name/clarabel_error.py", line 22, in simple_SOCP
    prob.solve(verbose=True)
  File "/home/cahit/micromamba/envs/torch/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/cahit/micromamba/envs/torch/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1090, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/cahit/micromamba/envs/torch/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1415, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'CLARABEL' failed. Try another solver, or solve with verbose=True for more information.
```

**Version**
 - OS: Ubuntu 22.04.3 LTS
 - CVXPY Version: 1.5.3

**Additional context**
-

**Comment by Transurgeon** [comment]
Thanks for raising this issue @cahity , we are aware that CLARABEL introduced some regressions compared to ECOS and SCS, but this is a new one. We will definitely be adding it to the test suite and letting the clarabel team know about this.

**Comment by cahity** [comment]
I looked at it again and created an even simpler case. Also checked for the same problem with a norm constraint instead of an SOC constraint. SCS says SOCP is not feasible (which is false), CLARABEL gives error in the SOCP case, and all other combinations (_i.e._, norm constraint with all solvers, and SOCP with ECOS) give correct and similar solutions. Very peculiar.
```python
def simple_SOCP():
    x = cp.Variable(1)

    diff = -0.6452
    soc_constraint = [cp.SOC(0.1, x + diff)]  # Error
    constraint = [cp.norm(x + diff) <= 0.1]   # No error

    prob = cp.Problem(cp.Minimize(0), soc_constraint)

    prob.solve()  # solver=cp.SCS, solver=cp.CLARABEL, solver=cp.ECOS
    return x.value is not None
```
It seems that only ECOS is consistent with the solution when the diff value changes, others come and go.

**Comment by goulart-paul** [comment]
This appears to be fixed now with v0.10.0, so this issue can probably be closed.
