### ISSUE TITLE
error "Resulting quadratic form does not have appropriate dimensions" when multiprocessing is used

### ISSUE THREAD

**Issue by edbarton1** [cvxpy/cvxpy#835]
One of the cvxpy examples gets an error about wrong dimensions for the resulting quadratic form, but only if it is run with multiprocessing.

The attached .py file has been renamed to .py.txt to allow attaching it.

[cvxpy-bug-lasso-multiprocessing.py.txt](https://github.com/cvxgrp/cvxpy/files/3714550/cvxpy-bug-lasso-multiprocessing.py.txt)

This is a modified copy of examples/admm_lasso.py from the cvxpy repo, repaired to run in Python 3 and with a conditional added to show the bug.

If the file is changed so that show_bug=False, the output is
```
ADMM best 30.196966517374065
ECOS best 30.027898655129338
```
and there is no error.

If the file is run as submitted, so that show_bug=True, then it dies with a runtime error:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/multiprocessing/pool.py", line 119, i worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/multiprocessing/pool.py", line 44, inmapstar
    return list(map(*args))
  File "cvxpy-bug-lasso-multiprocessing.py", line 22, in prox
    Problem(Minimize(f)).solve()
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/problems/problem.y", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/problems/problem.y", line 569, in _solve
    self._intermediate_problem)
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/reductions/chain.y", line 65, in apply
    problem, inv = r.apply(problem)
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/reductions/matrixstuffing.py", line 84, in apply
    new_obj, new_var, r = self.stuffed_objective(problem, extractor)
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/reductions/qp2qua_form/qp_matrix_stuffing.py", line 49, in stuffed_objective
    P, q, r = extractor.quad_form(expr)
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/site-packages/cvxpy/utilities/coeff_etractor.py", line 168, in quad_form
    raise RuntimeError("Resulting quadratic form does not have "
RuntimeError: Resulting quadratic form does not have appropriate dimensions
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cvxpy-bug-lasso-multiprocessing.py", line 41, in <module>
    xi = pool.map(prox, zip(funcs, prox_args))
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/multiprocessing/pool.py", line 288, i map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ubuntu/anaconda3/envs/edcvxenv1a/lib/python3.6/multiprocessing/pool.py", line 670, i get
    raise self._value
RuntimeError: Resulting quadratic form does not have appropriate dimensions
```

I am running Python 3.6.7 :: Anaconda, Inc. and cvxpy==1.0.25 on  Ubuntu 19.04.

EDIT (akshayka): I've copied your linked-to source below

```
# examples/admm_lasso.py example from github repo, slightly repaired
# and run in Python 3

# license notice removed

from cvxpy import *
import numpy as np
from multiprocessing import Pool

show_bug = True

# Problem data.
m = 100
n = 75
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

def prox(args):
    f, v = args
    f += (rho/2)*sum_squares(x - v)
    Problem(Minimize(f)).solve()
    return x.value

# Setup problem.
gamma = Parameter(nonneg=True)
gamma.value = 1
rho = 1.0
x = Variable(n)
funcs = [sum_squares(A*x - b),
         gamma*norm(x, 1)]
ui = [np.zeros(n) for func in funcs]
xbar = np.zeros(n)

NUM_PROCS = 2
pool = Pool(NUM_PROCS)
# ADMM loop.
for i in range(50):
    prox_args = [xbar - u for u in ui]
    if show_bug:
        xi = pool.map(prox, zip(funcs, prox_args))
    else:
        xi = [prox(tup) for tup in zip(funcs, prox_args)]
    xbar = sum(xi)/len(xi)
    ui = [u + x_ - xbar for x_, u in zip(xi, ui)]

# Compare ADMM with standard solver.
prob = Problem(Minimize(sum(funcs)))
result = prob.solve()
print("ADMM best", (sum_squares(np.dot(A, xbar) - b) + gamma*norm(xbar, 1)).value)
print("ECOS best", result)
```

**Comment by akshayka** [comment]
Thanks for reporting. One way to work around this issue would be to change

```
    Problem(Minimize(f)).solve()
```

to

```
    Problem(Minimize(f)).solve(ECOS)
```

The default code path (ie, the QP code path) appears to interact poorly with multiprocessing, as you've found.
